// Hand-maintained CGate 9.9 metadata for the retained product streams.
// Unknown server tables and fields are accepted; required layouts are validated at OPEN.
#include "moex/plaza2/cgate/plaza2_metadata.hpp"

#include <array>

namespace moex::plaza2::generated {
namespace {
constexpr std::array<TypeDescriptor, kTypeCount> kTypeDescriptors{{
    {"c12", ValueClass::kFixedString, 0, 0},
    {"c20", ValueClass::kFixedString, 0, 0},
    {"c25", ValueClass::kFixedString, 0, 0},
    {"c255", ValueClass::kFixedString, 0, 0},
    {"c3", ValueClass::kFixedString, 0, 0},
    {"c4", ValueClass::kFixedString, 0, 0},
    {"c4000", ValueClass::kFixedString, 0, 0},
    {"c64", ValueClass::kFixedString, 0, 0},
    {"c7", ValueClass::kFixedString, 0, 0},
    {"c75", ValueClass::kFixedString, 0, 0},
    {"c8", ValueClass::kFixedString, 0, 0},
    {"d16.5", ValueClass::kDecimal, 16, 5},
    {"d26.2", ValueClass::kDecimal, 26, 2},
    {"i1", ValueClass::kSignedInteger, 0, 0},
    {"i4", ValueClass::kSignedInteger, 0, 0},
    {"i8", ValueClass::kSignedInteger, 0, 0},
    {"t", ValueClass::kTimestamp, 0, 0},
    {"u8", ValueClass::kUnsignedInteger, 0, 0},
}};

constexpr std::array<StreamDescriptor, kStreamCount> kStreamDescriptors{{
    {StreamCode::kFortsTradeRepl, "FORTS_TRADE_REPL", 0, 6},
    {StreamCode::kFortsDealsRepl, "FORTS_DEALS_REPL", 6, 4},
    {StreamCode::kFortsUserorderbookRepl, "FORTS_USERORDERBOOK_REPL", 10, 6},
    {StreamCode::kFortsAggrRepl, "FORTS_AGGR##_REPL", 16, 2},
    {StreamCode::kFortsPosRepl, "FORTS_POS_REPL", 18, 3},
    {StreamCode::kFortsPartRepl, "FORTS_PART_REPL", 21, 3},
    {StreamCode::kFortsRefdataRepl, "FORTS_REFDATA_REPL", 24, 8},
    {StreamCode::kFortsSessionstateRepl, "FORTS_SESSIONSTATE_REPL", 32, 1},
    {StreamCode::kFortsInstrumentstateRepl, "FORTS_INSTRUMENTSTATE_REPL", 33, 1},
}};

constexpr std::array<TableDescriptor, kTableCount> kTableDescriptors{{
    {TableCode::kFortsTradeReplOrdersLog, 0x7344FBC6u, "FORTS_TRADE_REPL", "orders_log", 0, 25},
    {TableCode::kFortsTradeReplMultilegOrdersLog, 0x7344FBC6u, "FORTS_TRADE_REPL", "multileg_orders_log", 25, 25},
    {TableCode::kFortsTradeReplUserDeal, 0x7344FBC6u, "FORTS_TRADE_REPL", "user_deal", 50, 23},
    {TableCode::kFortsTradeReplUserMultilegDeal, 0x7344FBC6u, "FORTS_TRADE_REPL", "user_multileg_deal", 73, 24},
    {TableCode::kFortsTradeReplHeartbeat, 0x7344FBC6u, "FORTS_TRADE_REPL", "heartbeat", 97, 4},
    {TableCode::kFortsTradeReplSysEvents, 0x7344FBC6u, "FORTS_TRADE_REPL", "sys_events", 101, 8},
    {TableCode::kFortsDealsReplDeal, 0x271473DDu, "FORTS_DEALS_REPL", "deal", 109, 18},
    {TableCode::kFortsDealsReplMultilegDeal, 0x271473DDu, "FORTS_DEALS_REPL", "multileg_deal", 127, 10},
    {TableCode::kFortsDealsReplHeartbeat, 0x271473DDu, "FORTS_DEALS_REPL", "heartbeat", 137, 3},
    {TableCode::kFortsDealsReplSysEvents, 0x271473DDu, "FORTS_DEALS_REPL", "sys_events", 140, 5},
    {TableCode::kFortsUserorderbookReplOrders, 0x9854831Cu, "FORTS_USERORDERBOOK_REPL", "orders", 145, 24},
    {TableCode::kFortsUserorderbookReplMultilegOrders, 0x9854831Cu, "FORTS_USERORDERBOOK_REPL", "multileg_orders", 169,
     24},
    {TableCode::kFortsUserorderbookReplInfo, 0x9854831Cu, "FORTS_USERORDERBOOK_REPL", "info", 193, 7},
    {TableCode::kFortsUserorderbookReplOrdersCurrentday, 0x9854831Cu, "FORTS_USERORDERBOOK_REPL", "orders_currentday",
     200, 24},
    {TableCode::kFortsUserorderbookReplMultilegOrdersCurrentday, 0x9854831Cu, "FORTS_USERORDERBOOK_REPL",
     "multileg_orders_currentday", 224, 24},
    {TableCode::kFortsUserorderbookReplInfoCurrentday, 0x9854831Cu, "FORTS_USERORDERBOOK_REPL", "info_currentday", 248,
     7},
    {TableCode::kFortsAggrReplOrdersAggr, 0x20C18715u, "FORTS_AGGR##_REPL", "orders_aggr", 255, 10},
    {TableCode::kFortsAggrReplSysEvents, 0x20C18715u, "FORTS_AGGR##_REPL", "sys_events", 265, 8},
    {TableCode::kFortsPosReplPosition, 0x1E3EE282u, "FORTS_POS_REPL", "position", 273, 17},
    {TableCode::kFortsPosReplPositionSa, 0x1E3EE282u, "FORTS_POS_REPL", "position_sa", 290, 6},
    {TableCode::kFortsPosReplInfo, 0x1E3EE282u, "FORTS_POS_REPL", "info", 296, 6},
    {TableCode::kFortsPartReplPart, 0x29343FB7u, "FORTS_PART_REPL", "part", 302, 19},
    {TableCode::kFortsPartReplPartSa, 0x29343FB7u, "FORTS_PART_REPL", "part_sa", 321, 5},
    {TableCode::kFortsPartReplSysEvents, 0x29343FB7u, "FORTS_PART_REPL", "sys_events", 326, 8},
    {TableCode::kFortsRefdataReplFutSessContents, 0xF42AF31Fu, "FORTS_REFDATA_REPL", "fut_sess_contents", 334, 26},
    {TableCode::kFortsRefdataReplFutVcb, 0xF42AF31Fu, "FORTS_REFDATA_REPL", "fut_vcb", 360, 7},
    {TableCode::kFortsRefdataReplFutInstruments, 0xF42AF31Fu, "FORTS_REFDATA_REPL", "fut_instruments", 367, 21},
    {TableCode::kFortsRefdataReplSysMessages, 0xF42AF31Fu, "FORTS_REFDATA_REPL", "sys_messages", 388, 11},
    {TableCode::kFortsRefdataReplOptSessContents, 0xF42AF31Fu, "FORTS_REFDATA_REPL", "opt_sess_contents", 399, 21},
    {TableCode::kFortsRefdataReplMultilegDict, 0xF42AF31Fu, "FORTS_REFDATA_REPL", "multileg_dict", 420, 8},
    {TableCode::kFortsRefdataReplInstr2matchingMap, 0xF42AF31Fu, "FORTS_REFDATA_REPL", "instr2matching_map", 428, 5},
    {TableCode::kFortsRefdataReplSession, 0xF42AF31Fu, "FORTS_REFDATA_REPL", "session", 433, 21},
    {TableCode::kFortsSessionstateReplSessionState, 0x4C6EE2C3u, "FORTS_SESSIONSTATE_REPL", "session_state", 454, 5},
    {TableCode::kFortsInstrumentstateReplInstrumentState, 0x53AD8B6Au, "FORTS_INSTRUMENTSTATE_REPL", "instrument_state",
     459, 5},
}};

constexpr std::array<FieldDescriptor, kFieldCount> kFieldDescriptors{{
    {FieldCode::kFortsTradeReplOrdersLogReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsTradeReplOrdersLogReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsTradeReplOrdersLogReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsTradeReplOrdersLogPublicOrderId, "public_order_id", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     false},
    {FieldCode::kFortsTradeReplOrdersLogSessId, "sess_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsTradeReplOrdersLogIsinId, "isin_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsTradeReplOrdersLogPublicAmount, "public_amount", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     false},
    {FieldCode::kFortsTradeReplOrdersLogPublicAmountRest, "public_amount_rest", "i8", ValueClass::kSignedInteger, 8, 0,
     0, false},
    {FieldCode::kFortsTradeReplOrdersLogIdDeal, "id_deal", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsTradeReplOrdersLogXstatus, "xstatus", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsTradeReplOrdersLogXstatus2, "xstatus2", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsTradeReplOrdersLogPrice, "price", "d16.5", ValueClass::kDecimal, 0, 16, 5, false},
    {FieldCode::kFortsTradeReplOrdersLogMoment, "moment", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsTradeReplOrdersLogMomentNs, "moment_ns", "u8", ValueClass::kUnsignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsTradeReplOrdersLogDir, "dir", "i1", ValueClass::kSignedInteger, 1, 0, 0, false},
    {FieldCode::kFortsTradeReplOrdersLogPublicAction, "public_action", "i1", ValueClass::kSignedInteger, 1, 0, 0,
     false},
    {FieldCode::kFortsTradeReplOrdersLogClientCode, "client_code", "c7", ValueClass::kFixedString, 8, 0, 0, false},
    {FieldCode::kFortsTradeReplOrdersLogLoginFrom, "login_from", "c20", ValueClass::kFixedString, 21, 0, 0, false},
    {FieldCode::kFortsTradeReplOrdersLogComment, "comment", "c20", ValueClass::kFixedString, 21, 0, 0, false},
    {FieldCode::kFortsTradeReplOrdersLogExtId, "ext_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsTradeReplOrdersLogIdOrd1, "id_ord1", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsTradeReplOrdersLogPrivateOrderId, "private_order_id", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     false},
    {FieldCode::kFortsTradeReplOrdersLogPrivateAmount, "private_amount", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     false},
    {FieldCode::kFortsTradeReplOrdersLogPrivateAmountRest, "private_amount_rest", "i8", ValueClass::kSignedInteger, 8,
     0, 0, false},
    {FieldCode::kFortsTradeReplOrdersLogPrivateAction, "private_action", "i1", ValueClass::kSignedInteger, 1, 0, 0,
     false},
    {FieldCode::kFortsTradeReplMultilegOrdersLogReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsTradeReplMultilegOrdersLogReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsTradeReplMultilegOrdersLogReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsTradeReplMultilegOrdersLogPublicOrderId, "public_order_id", "i8", ValueClass::kSignedInteger, 8,
     0, 0, false},
    {FieldCode::kFortsTradeReplMultilegOrdersLogSessId, "sess_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsTradeReplMultilegOrdersLogIsinId, "isin_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsTradeReplMultilegOrdersLogPublicAmount, "public_amount", "i8", ValueClass::kSignedInteger, 8, 0,
     0, false},
    {FieldCode::kFortsTradeReplMultilegOrdersLogPublicAmountRest, "public_amount_rest", "i8",
     ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsTradeReplMultilegOrdersLogIdDeal, "id_deal", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsTradeReplMultilegOrdersLogXstatus, "xstatus", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsTradeReplMultilegOrdersLogXstatus2, "xstatus2", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsTradeReplMultilegOrdersLogPrice, "price", "d16.5", ValueClass::kDecimal, 0, 16, 5, false},
    {FieldCode::kFortsTradeReplMultilegOrdersLogMoment, "moment", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsTradeReplMultilegOrdersLogMomentNs, "moment_ns", "u8", ValueClass::kUnsignedInteger, 8, 0, 0,
     false},
    {FieldCode::kFortsTradeReplMultilegOrdersLogDir, "dir", "i1", ValueClass::kSignedInteger, 1, 0, 0, false},
    {FieldCode::kFortsTradeReplMultilegOrdersLogPublicAction, "public_action", "i1", ValueClass::kSignedInteger, 1, 0,
     0, false},
    {FieldCode::kFortsTradeReplMultilegOrdersLogClientCode, "client_code", "c7", ValueClass::kFixedString, 8, 0, 0,
     false},
    {FieldCode::kFortsTradeReplMultilegOrdersLogLoginFrom, "login_from", "c20", ValueClass::kFixedString, 21, 0, 0,
     false},
    {FieldCode::kFortsTradeReplMultilegOrdersLogComment, "comment", "c20", ValueClass::kFixedString, 21, 0, 0, false},
    {FieldCode::kFortsTradeReplMultilegOrdersLogExtId, "ext_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsTradeReplMultilegOrdersLogIdOrd1, "id_ord1", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsTradeReplMultilegOrdersLogPrivateOrderId, "private_order_id", "i8", ValueClass::kSignedInteger, 8,
     0, 0, false},
    {FieldCode::kFortsTradeReplMultilegOrdersLogPrivateAmount, "private_amount", "i8", ValueClass::kSignedInteger, 8, 0,
     0, false},
    {FieldCode::kFortsTradeReplMultilegOrdersLogPrivateAmountRest, "private_amount_rest", "i8",
     ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsTradeReplMultilegOrdersLogPrivateAction, "private_action", "i1", ValueClass::kSignedInteger, 1, 0,
     0, false},
    {FieldCode::kFortsTradeReplUserDealReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsTradeReplUserDealReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsTradeReplUserDealReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsTradeReplUserDealSessId, "sess_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsTradeReplUserDealIsinId, "isin_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsTradeReplUserDealIdDeal, "id_deal", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsTradeReplUserDealXpos, "xpos", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsTradeReplUserDealXamount, "xamount", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsTradeReplUserDealPublicOrderIdBuy, "public_order_id_buy", "i8", ValueClass::kSignedInteger, 8, 0,
     0, false},
    {FieldCode::kFortsTradeReplUserDealPublicOrderIdSell, "public_order_id_sell", "i8", ValueClass::kSignedInteger, 8,
     0, 0, false},
    {FieldCode::kFortsTradeReplUserDealPrice, "price", "d16.5", ValueClass::kDecimal, 0, 16, 5, false},
    {FieldCode::kFortsTradeReplUserDealMoment, "moment", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsTradeReplUserDealMomentNs, "moment_ns", "u8", ValueClass::kUnsignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsTradeReplUserDealExtIdBuy, "ext_id_buy", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsTradeReplUserDealExtIdSell, "ext_id_sell", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsTradeReplUserDealCodeBuy, "code_buy", "c7", ValueClass::kFixedString, 8, 0, 0, false},
    {FieldCode::kFortsTradeReplUserDealCodeSell, "code_sell", "c7", ValueClass::kFixedString, 8, 0, 0, false},
    {FieldCode::kFortsTradeReplUserDealCommentBuy, "comment_buy", "c20", ValueClass::kFixedString, 21, 0, 0, false},
    {FieldCode::kFortsTradeReplUserDealCommentSell, "comment_sell", "c20", ValueClass::kFixedString, 21, 0, 0, false},
    {FieldCode::kFortsTradeReplUserDealLoginBuy, "login_buy", "c20", ValueClass::kFixedString, 21, 0, 0, false},
    {FieldCode::kFortsTradeReplUserDealLoginSell, "login_sell", "c20", ValueClass::kFixedString, 21, 0, 0, false},
    {FieldCode::kFortsTradeReplUserDealPrivateOrderIdBuy, "private_order_id_buy", "i8", ValueClass::kSignedInteger, 8,
     0, 0, false},
    {FieldCode::kFortsTradeReplUserDealPrivateOrderIdSell, "private_order_id_sell", "i8", ValueClass::kSignedInteger, 8,
     0, 0, false},
    {FieldCode::kFortsTradeReplUserMultilegDealReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsTradeReplUserMultilegDealReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsTradeReplUserMultilegDealReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsTradeReplUserMultilegDealSessId, "sess_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsTradeReplUserMultilegDealIsinId, "isin_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsTradeReplUserMultilegDealIdDeal, "id_deal", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsTradeReplUserMultilegDealPublicOrderIdBuy, "public_order_id_buy", "i8",
     ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsTradeReplUserMultilegDealPublicOrderIdSell, "public_order_id_sell", "i8",
     ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsTradeReplUserMultilegDealXamount, "xamount", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsTradeReplUserMultilegDealPrice, "price", "d16.5", ValueClass::kDecimal, 0, 16, 5, false},
    {FieldCode::kFortsTradeReplUserMultilegDealRatePrice, "rate_price", "d16.5", ValueClass::kDecimal, 0, 16, 5, false},
    {FieldCode::kFortsTradeReplUserMultilegDealSwapPrice, "swap_price", "d16.5", ValueClass::kDecimal, 0, 16, 5, false},
    {FieldCode::kFortsTradeReplUserMultilegDealMoment, "moment", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsTradeReplUserMultilegDealMomentNs, "moment_ns", "u8", ValueClass::kUnsignedInteger, 8, 0, 0,
     false},
    {FieldCode::kFortsTradeReplUserMultilegDealExtIdBuy, "ext_id_buy", "i4", ValueClass::kSignedInteger, 4, 0, 0,
     false},
    {FieldCode::kFortsTradeReplUserMultilegDealExtIdSell, "ext_id_sell", "i4", ValueClass::kSignedInteger, 4, 0, 0,
     false},
    {FieldCode::kFortsTradeReplUserMultilegDealCodeBuy, "code_buy", "c7", ValueClass::kFixedString, 8, 0, 0, false},
    {FieldCode::kFortsTradeReplUserMultilegDealCodeSell, "code_sell", "c7", ValueClass::kFixedString, 8, 0, 0, false},
    {FieldCode::kFortsTradeReplUserMultilegDealCommentBuy, "comment_buy", "c20", ValueClass::kFixedString, 21, 0, 0,
     false},
    {FieldCode::kFortsTradeReplUserMultilegDealCommentSell, "comment_sell", "c20", ValueClass::kFixedString, 21, 0, 0,
     false},
    {FieldCode::kFortsTradeReplUserMultilegDealLoginBuy, "login_buy", "c20", ValueClass::kFixedString, 21, 0, 0, false},
    {FieldCode::kFortsTradeReplUserMultilegDealLoginSell, "login_sell", "c20", ValueClass::kFixedString, 21, 0, 0,
     false},
    {FieldCode::kFortsTradeReplUserMultilegDealPrivateOrderIdBuy, "private_order_id_buy", "i8",
     ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsTradeReplUserMultilegDealPrivateOrderIdSell, "private_order_id_sell", "i8",
     ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsTradeReplHeartbeatReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsTradeReplHeartbeatReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsTradeReplHeartbeatReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsTradeReplHeartbeatServerTime, "server_time", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsTradeReplSysEventsReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsTradeReplSysEventsReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsTradeReplSysEventsReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsTradeReplSysEventsEventId, "event_id", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsTradeReplSysEventsSessId, "sess_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsTradeReplSysEventsEventType, "event_type", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsTradeReplSysEventsMessage, "message", "c64", ValueClass::kFixedString, 65, 0, 0, false},
    {FieldCode::kFortsTradeReplSysEventsServerTime, "server_time", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsDealsReplDealReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsDealsReplDealReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsDealsReplDealReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsDealsReplDealSessId, "sess_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsDealsReplDealIsinId, "isin_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsDealsReplDealIdDeal, "id_deal", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsDealsReplDealXpos, "xpos", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsDealsReplDealXamount, "xamount", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsDealsReplDealPublicOrderIdBuy, "public_order_id_buy", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     false},
    {FieldCode::kFortsDealsReplDealPublicOrderIdSell, "public_order_id_sell", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     false},
    {FieldCode::kFortsDealsReplDealPrice, "price", "d16.5", ValueClass::kDecimal, 0, 16, 5, false},
    {FieldCode::kFortsDealsReplDealMoment, "moment", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsDealsReplDealMomentNs, "moment_ns", "u8", ValueClass::kUnsignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsDealsReplDealNosystem, "nosystem", "i1", ValueClass::kSignedInteger, 1, 0, 0, false},
    {FieldCode::kFortsDealsReplDealXstatusBuy, "xstatus_buy", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsDealsReplDealXstatusSell, "xstatus_sell", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsDealsReplDealXstatus2Buy, "xstatus2_buy", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsDealsReplDealXstatus2Sell, "xstatus2_sell", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsDealsReplMultilegDealReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsDealsReplMultilegDealReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsDealsReplMultilegDealReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsDealsReplMultilegDealSessId, "sess_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsDealsReplMultilegDealIsinId, "isin_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsDealsReplMultilegDealIdDeal, "id_deal", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsDealsReplMultilegDealPublicOrderIdBuy, "public_order_id_buy", "i8", ValueClass::kSignedInteger, 8,
     0, 0, false},
    {FieldCode::kFortsDealsReplMultilegDealPublicOrderIdSell, "public_order_id_sell", "i8", ValueClass::kSignedInteger,
     8, 0, 0, false},
    {FieldCode::kFortsDealsReplMultilegDealXamount, "xamount", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsDealsReplMultilegDealPrice, "price", "d16.5", ValueClass::kDecimal, 0, 16, 5, false},
    {FieldCode::kFortsDealsReplHeartbeatReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsDealsReplHeartbeatReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsDealsReplHeartbeatReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsDealsReplSysEventsReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsDealsReplSysEventsReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsDealsReplSysEventsReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsDealsReplSysEventsSessId, "sess_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsDealsReplSysEventsEventType, "event_type", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplOrdersReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsUserorderbookReplOrdersReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsUserorderbookReplOrdersReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsUserorderbookReplOrdersPublicOrderId, "public_order_id", "i8", ValueClass::kSignedInteger, 8, 0,
     0, false},
    {FieldCode::kFortsUserorderbookReplOrdersSessId, "sess_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplOrdersClientCode, "client_code", "c7", ValueClass::kFixedString, 8, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplOrdersMoment, "moment", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplOrdersMomentNs, "moment_ns", "u8", ValueClass::kUnsignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplOrdersXstatus, "xstatus", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplOrdersXstatus2, "xstatus2", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplOrdersPublicAction, "public_action", "i1", ValueClass::kSignedInteger, 1, 0, 0,
     false},
    {FieldCode::kFortsUserorderbookReplOrdersIsinId, "isin_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplOrdersDir, "dir", "i1", ValueClass::kSignedInteger, 1, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplOrdersPrice, "price", "d16.5", ValueClass::kDecimal, 0, 16, 5, false},
    {FieldCode::kFortsUserorderbookReplOrdersPublicAmount, "public_amount", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     false},
    {FieldCode::kFortsUserorderbookReplOrdersPublicAmountRest, "public_amount_rest", "i8", ValueClass::kSignedInteger,
     8, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplOrdersComment, "comment", "c20", ValueClass::kFixedString, 21, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplOrdersExtId, "ext_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplOrdersLoginFrom, "login_from", "c20", ValueClass::kFixedString, 21, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplOrdersIdOrd1, "id_ord1", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplOrdersPrivateOrderId, "private_order_id", "i8", ValueClass::kSignedInteger, 8, 0,
     0, false},
    {FieldCode::kFortsUserorderbookReplOrdersPrivateAmount, "private_amount", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     false},
    {FieldCode::kFortsUserorderbookReplOrdersPrivateAmountRest, "private_amount_rest", "i8", ValueClass::kSignedInteger,
     8, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplOrdersPrivateAction, "private_action", "i1", ValueClass::kSignedInteger, 1, 0, 0,
     false},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     true},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     true},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersPublicOrderId, "public_order_id", "i8", ValueClass::kSignedInteger,
     8, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersSessId, "sess_id", "i4", ValueClass::kSignedInteger, 4, 0, 0,
     false},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersClientCode, "client_code", "c7", ValueClass::kFixedString, 8, 0, 0,
     false},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersMoment, "moment", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersMomentNs, "moment_ns", "u8", ValueClass::kUnsignedInteger, 8, 0, 0,
     false},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersXstatus, "xstatus", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     false},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersXstatus2, "xstatus2", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     false},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersPublicAction, "public_action", "i1", ValueClass::kSignedInteger, 1,
     0, 0, false},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersIsinId, "isin_id", "i4", ValueClass::kSignedInteger, 4, 0, 0,
     false},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersDir, "dir", "i1", ValueClass::kSignedInteger, 1, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersPrice, "price", "d16.5", ValueClass::kDecimal, 0, 16, 5, false},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersPublicAmount, "public_amount", "i8", ValueClass::kSignedInteger, 8,
     0, 0, false},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersPublicAmountRest, "public_amount_rest", "i8",
     ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersComment, "comment", "c20", ValueClass::kFixedString, 21, 0, 0,
     false},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersExtId, "ext_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersLoginFrom, "login_from", "c20", ValueClass::kFixedString, 21, 0, 0,
     false},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersIdOrd1, "id_ord1", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     false},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersPrivateOrderId, "private_order_id", "i8",
     ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersPrivateAmount, "private_amount", "i8", ValueClass::kSignedInteger,
     8, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersPrivateAmountRest, "private_amount_rest", "i8",
     ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersPrivateAction, "private_action", "i1", ValueClass::kSignedInteger,
     1, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplInfoReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsUserorderbookReplInfoReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsUserorderbookReplInfoReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsUserorderbookReplInfoMoment, "moment", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplInfoPublicationState, "publication_state", "i1", ValueClass::kSignedInteger, 1,
     0, 0, false},
    {FieldCode::kFortsUserorderbookReplInfoTradesRev, "trades_rev", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplInfoTradesLifenum, "trades_lifenum", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     false},
    {FieldCode::kFortsUserorderbookReplOrdersCurrentdayReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     true},
    {FieldCode::kFortsUserorderbookReplOrdersCurrentdayReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     true},
    {FieldCode::kFortsUserorderbookReplOrdersCurrentdayReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     true},
    {FieldCode::kFortsUserorderbookReplOrdersCurrentdayPublicOrderId, "public_order_id", "i8",
     ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplOrdersCurrentdaySessId, "sess_id", "i4", ValueClass::kSignedInteger, 4, 0, 0,
     false},
    {FieldCode::kFortsUserorderbookReplOrdersCurrentdayClientCode, "client_code", "c7", ValueClass::kFixedString, 8, 0,
     0, false},
    {FieldCode::kFortsUserorderbookReplOrdersCurrentdayMoment, "moment", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplOrdersCurrentdayMomentNs, "moment_ns", "u8", ValueClass::kUnsignedInteger, 8, 0,
     0, false},
    {FieldCode::kFortsUserorderbookReplOrdersCurrentdayXstatus, "xstatus", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     false},
    {FieldCode::kFortsUserorderbookReplOrdersCurrentdayXstatus2, "xstatus2", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     false},
    {FieldCode::kFortsUserorderbookReplOrdersCurrentdayPublicAction, "public_action", "i1", ValueClass::kSignedInteger,
     1, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplOrdersCurrentdayIsinId, "isin_id", "i4", ValueClass::kSignedInteger, 4, 0, 0,
     false},
    {FieldCode::kFortsUserorderbookReplOrdersCurrentdayDir, "dir", "i1", ValueClass::kSignedInteger, 1, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplOrdersCurrentdayPrice, "price", "d16.5", ValueClass::kDecimal, 0, 16, 5, false},
    {FieldCode::kFortsUserorderbookReplOrdersCurrentdayPublicAmount, "public_amount", "i8", ValueClass::kSignedInteger,
     8, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplOrdersCurrentdayPublicAmountRest, "public_amount_rest", "i8",
     ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplOrdersCurrentdayComment, "comment", "c20", ValueClass::kFixedString, 21, 0, 0,
     false},
    {FieldCode::kFortsUserorderbookReplOrdersCurrentdayExtId, "ext_id", "i4", ValueClass::kSignedInteger, 4, 0, 0,
     false},
    {FieldCode::kFortsUserorderbookReplOrdersCurrentdayLoginFrom, "login_from", "c20", ValueClass::kFixedString, 21, 0,
     0, false},
    {FieldCode::kFortsUserorderbookReplOrdersCurrentdayIdOrd1, "id_ord1", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     false},
    {FieldCode::kFortsUserorderbookReplOrdersCurrentdayPrivateOrderId, "private_order_id", "i8",
     ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplOrdersCurrentdayPrivateAmount, "private_amount", "i8",
     ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplOrdersCurrentdayPrivateAmountRest, "private_amount_rest", "i8",
     ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplOrdersCurrentdayPrivateAction, "private_action", "i1",
     ValueClass::kSignedInteger, 1, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersCurrentdayReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0,
     0, true},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersCurrentdayReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8,
     0, 0, true},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersCurrentdayReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8,
     0, 0, true},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersCurrentdayPublicOrderId, "public_order_id", "i8",
     ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersCurrentdaySessId, "sess_id", "i4", ValueClass::kSignedInteger, 4,
     0, 0, false},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersCurrentdayClientCode, "client_code", "c7",
     ValueClass::kFixedString, 8, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersCurrentdayMoment, "moment", "t", ValueClass::kTimestamp, 0, 0, 0,
     false},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersCurrentdayMomentNs, "moment_ns", "u8",
     ValueClass::kUnsignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersCurrentdayXstatus, "xstatus", "i8", ValueClass::kSignedInteger, 8,
     0, 0, false},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersCurrentdayXstatus2, "xstatus2", "i8", ValueClass::kSignedInteger,
     8, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersCurrentdayPublicAction, "public_action", "i1",
     ValueClass::kSignedInteger, 1, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersCurrentdayIsinId, "isin_id", "i4", ValueClass::kSignedInteger, 4,
     0, 0, false},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersCurrentdayDir, "dir", "i1", ValueClass::kSignedInteger, 1, 0, 0,
     false},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersCurrentdayPrice, "price", "d16.5", ValueClass::kDecimal, 0, 16, 5,
     false},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersCurrentdayPublicAmount, "public_amount", "i8",
     ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersCurrentdayPublicAmountRest, "public_amount_rest", "i8",
     ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersCurrentdayComment, "comment", "c20", ValueClass::kFixedString, 21,
     0, 0, false},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersCurrentdayExtId, "ext_id", "i4", ValueClass::kSignedInteger, 4, 0,
     0, false},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersCurrentdayLoginFrom, "login_from", "c20", ValueClass::kFixedString,
     21, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersCurrentdayIdOrd1, "id_ord1", "i8", ValueClass::kSignedInteger, 8,
     0, 0, false},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersCurrentdayPrivateOrderId, "private_order_id", "i8",
     ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersCurrentdayPrivateAmount, "private_amount", "i8",
     ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersCurrentdayPrivateAmountRest, "private_amount_rest", "i8",
     ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplMultilegOrdersCurrentdayPrivateAction, "private_action", "i1",
     ValueClass::kSignedInteger, 1, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplInfoCurrentdayReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsUserorderbookReplInfoCurrentdayReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     true},
    {FieldCode::kFortsUserorderbookReplInfoCurrentdayReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     true},
    {FieldCode::kFortsUserorderbookReplInfoCurrentdayPublicationState, "publication_state", "i1",
     ValueClass::kSignedInteger, 1, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplInfoCurrentdayTradesRev, "trades_rev", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     false},
    {FieldCode::kFortsUserorderbookReplInfoCurrentdayTradesLifenum, "trades_lifenum", "i8", ValueClass::kSignedInteger,
     8, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplInfoCurrentdayServerTime, "server_time", "t", ValueClass::kTimestamp, 0, 0, 0,
     false},
    {FieldCode::kFortsAggrReplOrdersAggrReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsAggrReplOrdersAggrReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsAggrReplOrdersAggrReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsAggrReplOrdersAggrIsinId, "isin_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsAggrReplOrdersAggrPrice, "price", "d16.5", ValueClass::kDecimal, 0, 16, 5, false},
    {FieldCode::kFortsAggrReplOrdersAggrVolume, "volume", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsAggrReplOrdersAggrMoment, "moment", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsAggrReplOrdersAggrMomentNs, "moment_ns", "u8", ValueClass::kUnsignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsAggrReplOrdersAggrDir, "dir", "i1", ValueClass::kSignedInteger, 1, 0, 0, false},
    {FieldCode::kFortsAggrReplOrdersAggrSynthVolume, "synth_volume", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsAggrReplSysEventsReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsAggrReplSysEventsReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsAggrReplSysEventsReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsAggrReplSysEventsEventType, "event_type", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsAggrReplSysEventsEventId, "event_id", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsAggrReplSysEventsSessId, "sess_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsAggrReplSysEventsMessage, "message", "c64", ValueClass::kFixedString, 65, 0, 0, false},
    {FieldCode::kFortsAggrReplSysEventsServerTime, "server_time", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsPosReplPositionReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsPosReplPositionReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsPosReplPositionReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsPosReplPositionClientCode, "client_code", "c7", ValueClass::kFixedString, 8, 0, 0, false},
    {FieldCode::kFortsPosReplPositionIsinId, "isin_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsPosReplPositionXpos, "xpos", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsPosReplPositionXbuysQty, "xbuys_qty", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsPosReplPositionXsellsQty, "xsells_qty", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsPosReplPositionXdayOpenQty, "xday_open_qty", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsPosReplPositionXdayOpenBuysQty, "xday_open_buys_qty", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     false},
    {FieldCode::kFortsPosReplPositionXdayOpenSellsQty, "xday_open_sells_qty", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     false},
    {FieldCode::kFortsPosReplPositionXopenQty, "xopen_qty", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsPosReplPositionWaprice, "waprice", "d16.5", ValueClass::kDecimal, 0, 16, 5, false},
    {FieldCode::kFortsPosReplPositionNetVolumeRur, "net_volume_rur", "d26.2", ValueClass::kDecimal, 0, 26, 2, false},
    {FieldCode::kFortsPosReplPositionLastDealId, "last_deal_id", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsPosReplPositionLastQuantity, "last_quantity", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsPosReplPositionAccountType, "account_type", "i1", ValueClass::kSignedInteger, 1, 0, 0, false},
    {FieldCode::kFortsPosReplPositionSaReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsPosReplPositionSaReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsPosReplPositionSaReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsPosReplPositionSaClientCode, "client_code", "c12", ValueClass::kFixedString, 13, 0, 0, false},
    {FieldCode::kFortsPosReplPositionSaIsinId, "isin_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsPosReplPositionSaXpos, "xpos", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsPosReplInfoReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsPosReplInfoReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsPosReplInfoReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsPosReplInfoTradesRev, "trades_rev", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsPosReplInfoTradesLifenum, "trades_lifenum", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsPosReplInfoServerTime, "server_time", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsPartReplPartReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsPartReplPartReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsPartReplPartReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsPartReplPartClientCode, "client_code", "c7", ValueClass::kFixedString, 8, 0, 0, false},
    {FieldCode::kFortsPartReplPartMoneyFree, "money_free", "d26.2", ValueClass::kDecimal, 0, 26, 2, false},
    {FieldCode::kFortsPartReplPartMoneyBlocked, "money_blocked", "d26.2", ValueClass::kDecimal, 0, 26, 2, false},
    {FieldCode::kFortsPartReplPartVmReserve, "vm_reserve", "d26.2", ValueClass::kDecimal, 0, 26, 2, false},
    {FieldCode::kFortsPartReplPartFee, "fee", "d26.2", ValueClass::kDecimal, 0, 26, 2, false},
    {FieldCode::kFortsPartReplPartLimitsSet, "limits_set", "i1", ValueClass::kSignedInteger, 1, 0, 0, false},
    {FieldCode::kFortsPartReplPartMoneyOld, "money_old", "d26.2", ValueClass::kDecimal, 0, 26, 2, false},
    {FieldCode::kFortsPartReplPartMoneyAmount, "money_amount", "d26.2", ValueClass::kDecimal, 0, 26, 2, false},
    {FieldCode::kFortsPartReplPartMoneyPledgeAmount, "money_pledge_amount", "d26.2", ValueClass::kDecimal, 0, 26, 2,
     false},
    {FieldCode::kFortsPartReplPartActualAmountOfBaseCurrency, "actual_amount_of_base_currency", "d26.2",
     ValueClass::kDecimal, 0, 26, 2, false},
    {FieldCode::kFortsPartReplPartVmIntercl, "vm_intercl", "d26.2", ValueClass::kDecimal, 0, 26, 2, false},
    {FieldCode::kFortsPartReplPartIsAutoUpdateLimit, "is_auto_update_limit", "i1", ValueClass::kSignedInteger, 1, 0, 0,
     false},
    {FieldCode::kFortsPartReplPartBrokerFee, "broker_fee", "d26.2", ValueClass::kDecimal, 0, 26, 2, false},
    {FieldCode::kFortsPartReplPartPenalty, "penalty", "d26.2", ValueClass::kDecimal, 0, 26, 2, false},
    {FieldCode::kFortsPartReplPartPremiumIntercl, "premium_intercl", "d26.2", ValueClass::kDecimal, 0, 26, 2, false},
    {FieldCode::kFortsPartReplPartNetOptionValue, "net_option_value", "d26.2", ValueClass::kDecimal, 0, 26, 2, false},
    {FieldCode::kFortsPartReplPartSaReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsPartReplPartSaReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsPartReplPartSaReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsPartReplPartSaMoneyAmount, "money_amount", "d26.2", ValueClass::kDecimal, 0, 26, 2, false},
    {FieldCode::kFortsPartReplPartSaMoneyFree, "money_free", "d26.2", ValueClass::kDecimal, 0, 26, 2, false},
    {FieldCode::kFortsPartReplSysEventsReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsPartReplSysEventsReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsPartReplSysEventsReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsPartReplSysEventsEventType, "event_type", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsPartReplSysEventsEventId, "event_id", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsPartReplSysEventsSessId, "sess_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsPartReplSysEventsMessage, "message", "c64", ValueClass::kFixedString, 65, 0, 0, false},
    {FieldCode::kFortsPartReplSysEventsServerTime, "server_time", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsRefdataReplFutSessContentsReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsRefdataReplFutSessContentsReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsRefdataReplFutSessContentsReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsRefdataReplFutSessContentsSessId, "sess_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsRefdataReplFutSessContentsIsinId, "isin_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsRefdataReplFutSessContentsShortIsin, "short_isin", "c25", ValueClass::kFixedString, 26, 0, 0,
     false},
    {FieldCode::kFortsRefdataReplFutSessContentsIsin, "isin", "c25", ValueClass::kFixedString, 26, 0, 0, false},
    {FieldCode::kFortsRefdataReplFutSessContentsName, "name", "c75", ValueClass::kFixedString, 76, 0, 0, false},
    {FieldCode::kFortsRefdataReplFutSessContentsInstTerm, "inst_term", "i4", ValueClass::kSignedInteger, 4, 0, 0,
     false},
    {FieldCode::kFortsRefdataReplFutSessContentsBaseContractCode, "base_contract_code", "c25", ValueClass::kFixedString,
     26, 0, 0, false},
    {FieldCode::kFortsRefdataReplFutSessContentsLimitUp, "limit_up", "d16.5", ValueClass::kDecimal, 0, 16, 5, false},
    {FieldCode::kFortsRefdataReplFutSessContentsLimitDown, "limit_down", "d16.5", ValueClass::kDecimal, 0, 16, 5,
     false},
    {FieldCode::kFortsRefdataReplFutSessContentsSettlementPriceOpen, "settlement_price_open", "d16.5",
     ValueClass::kDecimal, 0, 16, 5, false},
    {FieldCode::kFortsRefdataReplFutSessContentsRoundto, "roundto", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsRefdataReplFutSessContentsMinStep, "min_step", "d16.5", ValueClass::kDecimal, 0, 16, 5, false},
    {FieldCode::kFortsRefdataReplFutSessContentsLotVolume, "lot_volume", "i4", ValueClass::kSignedInteger, 4, 0, 0,
     false},
    {FieldCode::kFortsRefdataReplFutSessContentsStepPrice, "step_price", "d16.5", ValueClass::kDecimal, 0, 16, 5,
     false},
    {FieldCode::kFortsRefdataReplFutSessContentsLastTradeDate, "last_trade_date", "t", ValueClass::kTimestamp, 0, 0, 0,
     false},
    {FieldCode::kFortsRefdataReplFutSessContentsIsSpread, "is_spread", "i1", ValueClass::kSignedInteger, 1, 0, 0,
     false},
    {FieldCode::kFortsRefdataReplFutSessContentsSettlementPrice, "settlement_price", "d16.5", ValueClass::kDecimal, 0,
     16, 5, false},
    {FieldCode::kFortsRefdataReplFutSessContentsSigns, "signs", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsRefdataReplFutSessContentsState, "state", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsRefdataReplFutSessContentsStepPriceCurr, "step_price_curr", "d16.5", ValueClass::kDecimal, 0, 16,
     5, false},
    {FieldCode::kFortsRefdataReplFutSessContentsTradeModeId, "trade_mode_id", "i4", ValueClass::kSignedInteger, 4, 0, 0,
     false},
    {FieldCode::kFortsRefdataReplFutSessContentsGroupMask, "group_mask", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     false},
    {FieldCode::kFortsRefdataReplFutSessContentsTradePeriodAccess, "trade_period_access", "i8",
     ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsRefdataReplFutVcbReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsRefdataReplFutVcbReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsRefdataReplFutVcbReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsRefdataReplFutVcbBaseContractCode, "base_contract_code", "c25", ValueClass::kFixedString, 26, 0,
     0, false},
    {FieldCode::kFortsRefdataReplFutVcbCurr, "curr", "c3", ValueClass::kFixedString, 4, 0, 0, false},
    {FieldCode::kFortsRefdataReplFutVcbBaseContractId, "base_contract_id", "i4", ValueClass::kSignedInteger, 4, 0, 0,
     false},
    {FieldCode::kFortsRefdataReplFutVcbBoardMd, "board_md", "c4", ValueClass::kFixedString, 5, 0, 0, false},
    {FieldCode::kFortsRefdataReplFutInstrumentsReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsRefdataReplFutInstrumentsReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsRefdataReplFutInstrumentsReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsRefdataReplFutInstrumentsIsinId, "isin_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsRefdataReplFutInstrumentsShortIsin, "short_isin", "c25", ValueClass::kFixedString, 26, 0, 0,
     false},
    {FieldCode::kFortsRefdataReplFutInstrumentsIsin, "isin", "c25", ValueClass::kFixedString, 26, 0, 0, false},
    {FieldCode::kFortsRefdataReplFutInstrumentsName, "name", "c75", ValueClass::kFixedString, 76, 0, 0, false},
    {FieldCode::kFortsRefdataReplFutInstrumentsInstTerm, "inst_term", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsRefdataReplFutInstrumentsBaseContractCode, "base_contract_code", "c25", ValueClass::kFixedString,
     26, 0, 0, false},
    {FieldCode::kFortsRefdataReplFutInstrumentsRoundto, "roundto", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsRefdataReplFutInstrumentsMinStep, "min_step", "d16.5", ValueClass::kDecimal, 0, 16, 5, false},
    {FieldCode::kFortsRefdataReplFutInstrumentsLotVolume, "lot_volume", "i4", ValueClass::kSignedInteger, 4, 0, 0,
     false},
    {FieldCode::kFortsRefdataReplFutInstrumentsStepPrice, "step_price", "d16.5", ValueClass::kDecimal, 0, 16, 5, false},
    {FieldCode::kFortsRefdataReplFutInstrumentsLastTradeDate, "last_trade_date", "t", ValueClass::kTimestamp, 0, 0, 0,
     false},
    {FieldCode::kFortsRefdataReplFutInstrumentsIsSpread, "is_spread", "i1", ValueClass::kSignedInteger, 1, 0, 0, false},
    {FieldCode::kFortsRefdataReplFutInstrumentsSettlementPrice, "settlement_price", "d16.5", ValueClass::kDecimal, 0,
     16, 5, false},
    {FieldCode::kFortsRefdataReplFutInstrumentsSigns, "signs", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsRefdataReplFutInstrumentsStepPriceCurr, "step_price_curr", "d16.5", ValueClass::kDecimal, 0, 16,
     5, false},
    {FieldCode::kFortsRefdataReplFutInstrumentsTradeModeId, "trade_mode_id", "i4", ValueClass::kSignedInteger, 4, 0, 0,
     false},
    {FieldCode::kFortsRefdataReplFutInstrumentsGroupMask, "group_mask", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     false},
    {FieldCode::kFortsRefdataReplFutInstrumentsTradePeriodAccess, "trade_period_access", "i8",
     ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsRefdataReplSysMessagesReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsRefdataReplSysMessagesReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsRefdataReplSysMessagesReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsRefdataReplSysMessagesMsgId, "msg_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsRefdataReplSysMessagesLangCode, "lang_code", "c8", ValueClass::kFixedString, 9, 0, 0, false},
    {FieldCode::kFortsRefdataReplSysMessagesTypeId, "type_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsRefdataReplSysMessagesMoment, "moment", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsRefdataReplSysMessagesText, "text", "c255", ValueClass::kFixedString, 256, 0, 0, false},
    {FieldCode::kFortsRefdataReplSysMessagesUrgency, "urgency", "i1", ValueClass::kSignedInteger, 1, 0, 0, false},
    {FieldCode::kFortsRefdataReplSysMessagesStatus, "status", "i1", ValueClass::kSignedInteger, 1, 0, 0, false},
    {FieldCode::kFortsRefdataReplSysMessagesMessageBody, "message_body", "c4000", ValueClass::kFixedString, 4001, 0, 0,
     false},
    {FieldCode::kFortsRefdataReplOptSessContentsReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsRefdataReplOptSessContentsReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsRefdataReplOptSessContentsReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsRefdataReplOptSessContentsSessId, "sess_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsRefdataReplOptSessContentsIsinId, "isin_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsRefdataReplOptSessContentsIsin, "isin", "c25", ValueClass::kFixedString, 26, 0, 0, false},
    {FieldCode::kFortsRefdataReplOptSessContentsShortIsin, "short_isin", "c25", ValueClass::kFixedString, 26, 0, 0,
     false},
    {FieldCode::kFortsRefdataReplOptSessContentsName, "name", "c75", ValueClass::kFixedString, 76, 0, 0, false},
    {FieldCode::kFortsRefdataReplOptSessContentsBaseContractCode, "base_contract_code", "c25", ValueClass::kFixedString,
     26, 0, 0, false},
    {FieldCode::kFortsRefdataReplOptSessContentsFutIsinId, "fut_isin_id", "i4", ValueClass::kSignedInteger, 4, 0, 0,
     false},
    {FieldCode::kFortsRefdataReplOptSessContentsPut, "put", "i1", ValueClass::kSignedInteger, 1, 0, 0, false},
    {FieldCode::kFortsRefdataReplOptSessContentsStrike, "strike", "d16.5", ValueClass::kDecimal, 0, 16, 5, false},
    {FieldCode::kFortsRefdataReplOptSessContentsRoundto, "roundto", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsRefdataReplOptSessContentsLastTradeDate, "last_trade_date", "t", ValueClass::kTimestamp, 0, 0, 0,
     false},
    {FieldCode::kFortsRefdataReplOptSessContentsSigns, "signs", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsRefdataReplOptSessContentsSettlementPrice, "settlement_price", "d16.5", ValueClass::kDecimal, 0,
     16, 5, false},
    {FieldCode::kFortsRefdataReplOptSessContentsOptionSeriesId, "option_series_id", "i4", ValueClass::kSignedInteger, 4,
     0, 0, false},
    {FieldCode::kFortsRefdataReplOptSessContentsState, "state", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsRefdataReplOptSessContentsTradeModeId, "trade_mode_id", "i4", ValueClass::kSignedInteger, 4, 0, 0,
     false},
    {FieldCode::kFortsRefdataReplOptSessContentsGroupMask, "group_mask", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     false},
    {FieldCode::kFortsRefdataReplOptSessContentsTradePeriodAccess, "trade_period_access", "i8",
     ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsRefdataReplMultilegDictReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsRefdataReplMultilegDictReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsRefdataReplMultilegDictReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsRefdataReplMultilegDictSessId, "sess_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsRefdataReplMultilegDictIsinId, "isin_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsRefdataReplMultilegDictIsinIdLeg, "isin_id_leg", "i4", ValueClass::kSignedInteger, 4, 0, 0,
     false},
    {FieldCode::kFortsRefdataReplMultilegDictQtyRatio, "qty_ratio", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsRefdataReplMultilegDictLegOrderNo, "leg_order_no", "i1", ValueClass::kSignedInteger, 1, 0, 0,
     false},
    {FieldCode::kFortsRefdataReplInstr2matchingMapReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsRefdataReplInstr2matchingMapReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsRefdataReplInstr2matchingMapReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsRefdataReplInstr2matchingMapBaseContractId, "base_contract_id", "i4", ValueClass::kSignedInteger,
     4, 0, 0, false},
    {FieldCode::kFortsRefdataReplInstr2matchingMapMatchingId, "matching_id", "i1", ValueClass::kSignedInteger, 1, 0, 0,
     false},
    {FieldCode::kFortsRefdataReplSessionReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsRefdataReplSessionReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsRefdataReplSessionReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsRefdataReplSessionSessId, "sess_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsRefdataReplSessionBegin, "begin", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsRefdataReplSessionEnd, "end", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsRefdataReplSessionState, "state", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsRefdataReplSessionInterClBegin, "inter_cl_begin", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsRefdataReplSessionInterClEnd, "inter_cl_end", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsRefdataReplSessionInterClState, "inter_cl_state", "i4", ValueClass::kSignedInteger, 4, 0, 0,
     false},
    {FieldCode::kFortsRefdataReplSessionEveOn, "eve_on", "i1", ValueClass::kSignedInteger, 1, 0, 0, false},
    {FieldCode::kFortsRefdataReplSessionEveBegin, "eve_begin", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsRefdataReplSessionEveEnd, "eve_end", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsRefdataReplSessionMonOn, "mon_on", "i1", ValueClass::kSignedInteger, 1, 0, 0, false},
    {FieldCode::kFortsRefdataReplSessionMonBegin, "mon_begin", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsRefdataReplSessionMonEnd, "mon_end", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsRefdataReplSessionSettlSessBegin, "settl_sess_begin", "t", ValueClass::kTimestamp, 0, 0, 0,
     false},
    {FieldCode::kFortsRefdataReplSessionClrSessBegin, "clr_sess_begin", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsRefdataReplSessionSettlPriceCalcTime, "settl_price_calc_time", "t", ValueClass::kTimestamp, 0, 0,
     0, false},
    {FieldCode::kFortsRefdataReplSessionSettlSessT1Begin, "settl_sess_t1_begin", "t", ValueClass::kTimestamp, 0, 0, 0,
     false},
    {FieldCode::kFortsRefdataReplSessionMarginCallFixSchedule, "margin_call_fix_schedule", "t", ValueClass::kTimestamp,
     0, 0, 0, false},
    {FieldCode::kFortsSessionstateReplSessionStateReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsSessionstateReplSessionStateReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsSessionstateReplSessionStateReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsSessionstateReplSessionStateSessId, "sess_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsSessionstateReplSessionStatePublicState, "public_state", "i4", ValueClass::kSignedInteger, 4, 0,
     0, false},
    {FieldCode::kFortsInstrumentstateReplInstrumentStateReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     true},
    {FieldCode::kFortsInstrumentstateReplInstrumentStateReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     true},
    {FieldCode::kFortsInstrumentstateReplInstrumentStateReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     true},
    {FieldCode::kFortsInstrumentstateReplInstrumentStateIsinId, "isin_id", "i4", ValueClass::kSignedInteger, 4, 0, 0,
     false},
    {FieldCode::kFortsInstrumentstateReplInstrumentStatePublicState, "public_state", "i4", ValueClass::kSignedInteger,
     4, 0, 0, false},
}};

} // namespace

std::span<const TypeDescriptor> TypeDescriptors() {
    return kTypeDescriptors;
}

std::span<const StreamDescriptor> StreamDescriptors() {
    return kStreamDescriptors;
}

std::span<const TableDescriptor> TableDescriptors() {
    return kTableDescriptors;
}

std::span<const FieldDescriptor> FieldDescriptors() {
    return kFieldDescriptors;
}

const TypeDescriptor* FindTypeByToken(std::string_view type_token) {
    for (const auto& descriptor : kTypeDescriptors) {
        if (descriptor.type_token == type_token) {
            return &descriptor;
        }
    }
    return nullptr;
}

const StreamDescriptor* FindStreamByCode(StreamCode stream_code) {
    for (const auto& descriptor : kStreamDescriptors) {
        if (descriptor.stream_code == stream_code) {
            return &descriptor;
        }
    }
    return nullptr;
}

const TableDescriptor* FindTableByCode(TableCode table_code) {
    for (const auto& descriptor : kTableDescriptors) {
        if (descriptor.table_code == table_code) {
            return &descriptor;
        }
    }
    return nullptr;
}

const FieldDescriptor* FindFieldByCode(FieldCode field_code) {
    for (const auto& descriptor : kFieldDescriptors) {
        if (descriptor.field_code == field_code) {
            return &descriptor;
        }
    }
    return nullptr;
}

std::span<const TableDescriptor> TablesForStream(StreamCode stream_code) {
    const auto* stream = FindStreamByCode(stream_code);
    if (stream == nullptr) {
        return {};
    }
    return std::span<const TableDescriptor>(kTableDescriptors.data() + stream->first_table_index, stream->table_count);
}

std::span<const FieldDescriptor> FieldsForTable(TableCode table_code) {
    const auto* table = FindTableByCode(table_code);
    if (table == nullptr) {
        return {};
    }
    return std::span<const FieldDescriptor>(kFieldDescriptors.data() + table->first_field_index, table->field_count);
}

} // namespace moex::plaza2::generated
