// Hand-maintained CGate 9.9 metadata for the retained product streams.
// Unknown server tables and fields are accepted; required layouts are validated at OPEN.
#include "moex/plaza2/cgate/plaza2_metadata.hpp"

#include <array>

namespace moex::plaza2::generated {
namespace {
constexpr std::array<TypeDescriptor, kTypeCount> kTypeDescriptors{{
    {"c12", ValueClass::kFixedString, 0, 0},
    {"c20", ValueClass::kFixedString, 0, 0},
    {"c25", ValueClass::kFixedString, 0, 0},
    {"c255", ValueClass::kFixedString, 0, 0},
    {"c3", ValueClass::kFixedString, 0, 0},
    {"c4", ValueClass::kFixedString, 0, 0},
    {"c4000", ValueClass::kFixedString, 0, 0},
    {"c64", ValueClass::kFixedString, 0, 0},
    {"c7", ValueClass::kFixedString, 0, 0},
    {"c75", ValueClass::kFixedString, 0, 0},
    {"c8", ValueClass::kFixedString, 0, 0},
    {"d16.5", ValueClass::kDecimal, 16, 5},
    {"d26.2", ValueClass::kDecimal, 26, 2},
    {"i1", ValueClass::kSignedInteger, 0, 0},
    {"i4", ValueClass::kSignedInteger, 0, 0},
    {"i8", ValueClass::kSignedInteger, 0, 0},
    {"t", ValueClass::kTimestamp, 0, 0},
    {"u8", ValueClass::kUnsignedInteger, 0, 0},
}};

constexpr std::array<StreamDescriptor, kStreamCount> kStreamDescriptors{{
    {StreamCode::kFortsTradeRepl, "FORTS_TRADE_REPL", 0, 6},
    {StreamCode::kFortsDealsRepl, "FORTS_DEALS_REPL", 6, 4},
    {StreamCode::kFortsUserorderbookRepl, "FORTS_USERORDERBOOK_REPL", 10, 6},
    {StreamCode::kFortsAggrRepl, "FORTS_AGGR##_REPL", 16, 2},
    {StreamCode::kFortsPosRepl, "FORTS_POS_REPL", 18, 3},
    {StreamCode::kFortsPartRepl, "FORTS_PART_REPL", 21, 3},
    {StreamCode::kFortsRefdataRepl, "FORTS_REFDATA_REPL", 24, 8},
    {StreamCode::kFortsSessionstateRepl, "FORTS_SESSIONSTATE_REPL", 32, 1},
    {StreamCode::kFortsInstrumentstateRepl, "FORTS_INSTRUMENTSTATE_REPL", 33, 1},
}};

constexpr std::array<TableDescriptor, kTableCount> kTableDescriptors{{
    {TableCode::kFortsTradeReplOrdersLog, 0x7344FBC6u, "FORTS_TRADE_REPL", "orders_log", 0, 26},
    {TableCode::kFortsTradeReplMultilegOrdersLog, 0x7344FBC6u, "FORTS_TRADE_REPL", "multileg_orders_log", 26, 0},
    {TableCode::kFortsTradeReplUserDeal, 0x7344FBC6u, "FORTS_TRADE_REPL", "user_deal", 26, 23},
    {TableCode::kFortsTradeReplUserMultilegDeal, 0x7344FBC6u, "FORTS_TRADE_REPL", "user_multileg_deal", 49, 0},
    {TableCode::kFortsTradeReplHeartbeat, 0x7344FBC6u, "FORTS_TRADE_REPL", "heartbeat", 49, 4},
    {TableCode::kFortsTradeReplSysEvents, 0x7344FBC6u, "FORTS_TRADE_REPL", "sys_events", 53, 8},
    {TableCode::kFortsDealsReplDeal, 0x271473DDu, "FORTS_DEALS_REPL", "deal", 61, 18},
    {TableCode::kFortsDealsReplMultilegDeal, 0x271473DDu, "FORTS_DEALS_REPL", "multileg_deal", 79, 10},
    {TableCode::kFortsDealsReplHeartbeat, 0x271473DDu, "FORTS_DEALS_REPL", "heartbeat", 89, 3},
    {TableCode::kFortsDealsReplSysEvents, 0x271473DDu, "FORTS_DEALS_REPL", "sys_events", 92, 5},
    {TableCode::kFortsUserorderbookReplOrders, 0x9854831Cu, "FORTS_USERORDERBOOK_REPL", "orders", 97, 24},
    {TableCode::kFortsUserorderbookReplMultilegOrders, 0x9854831Cu, "FORTS_USERORDERBOOK_REPL", "multileg_orders", 121,
     0},
    {TableCode::kFortsUserorderbookReplInfo, 0x9854831Cu, "FORTS_USERORDERBOOK_REPL", "info", 121, 7},
    {TableCode::kFortsUserorderbookReplOrdersCurrentday, 0x9854831Cu, "FORTS_USERORDERBOOK_REPL", "orders_currentday",
     128, 0},
    {TableCode::kFortsUserorderbookReplMultilegOrdersCurrentday, 0x9854831Cu, "FORTS_USERORDERBOOK_REPL",
     "multileg_orders_currentday", 128, 0},
    {TableCode::kFortsUserorderbookReplInfoCurrentday, 0x9854831Cu, "FORTS_USERORDERBOOK_REPL", "info_currentday", 128,
     0},
    {TableCode::kFortsAggrReplOrdersAggr, 0x20C18715u, "FORTS_AGGR##_REPL", "orders_aggr", 128, 10},
    {TableCode::kFortsAggrReplSysEvents, 0x20C18715u, "FORTS_AGGR##_REPL", "sys_events", 138, 8},
    {TableCode::kFortsPosReplPosition, 0x1E3EE282u, "FORTS_POS_REPL", "position", 146, 17},
    {TableCode::kFortsPosReplPositionSa, 0x1E3EE282u, "FORTS_POS_REPL", "position_sa", 163, 0},
    {TableCode::kFortsPosReplInfo, 0x1E3EE282u, "FORTS_POS_REPL", "info", 163, 6},
    {TableCode::kFortsPartReplPart, 0x29343FB7u, "FORTS_PART_REPL", "part", 169, 0},
    {TableCode::kFortsPartReplPartSa, 0x29343FB7u, "FORTS_PART_REPL", "part_sa", 169, 0},
    {TableCode::kFortsPartReplSysEvents, 0x29343FB7u, "FORTS_PART_REPL", "sys_events", 169, 8},
    {TableCode::kFortsRefdataReplFutSessContents, 0xF42AF31Fu, "FORTS_REFDATA_REPL", "fut_sess_contents", 177, 26},
    {TableCode::kFortsRefdataReplFutVcb, 0xF42AF31Fu, "FORTS_REFDATA_REPL", "fut_vcb", 203, 7},
    {TableCode::kFortsRefdataReplFutInstruments, 0xF42AF31Fu, "FORTS_REFDATA_REPL", "fut_instruments", 210, 21},
    {TableCode::kFortsRefdataReplSysMessages, 0xF42AF31Fu, "FORTS_REFDATA_REPL", "sys_messages", 231, 11},
    {TableCode::kFortsRefdataReplOptSessContents, 0xF42AF31Fu, "FORTS_REFDATA_REPL", "opt_sess_contents", 242, 0},
    {TableCode::kFortsRefdataReplMultilegDict, 0xF42AF31Fu, "FORTS_REFDATA_REPL", "multileg_dict", 242, 0},
    {TableCode::kFortsRefdataReplInstr2matchingMap, 0xF42AF31Fu, "FORTS_REFDATA_REPL", "instr2matching_map", 242, 0},
    {TableCode::kFortsRefdataReplSession, 0xF42AF31Fu, "FORTS_REFDATA_REPL", "session", 242, 21},
    {TableCode::kFortsSessionstateReplSessionState, 0x4C6EE2C3u, "FORTS_SESSIONSTATE_REPL", "session_state", 263, 5},
    {TableCode::kFortsInstrumentstateReplInstrumentState, 0x53AD8B6Au, "FORTS_INSTRUMENTSTATE_REPL", "instrument_state",
     268, 5},
}};

constexpr std::array<FieldDescriptor, kFieldCount> kFieldDescriptors{{
    {FieldCode::kFortsTradeReplOrdersLogReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsTradeReplOrdersLogReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsTradeReplOrdersLogReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsTradeReplOrdersLogPublicOrderId, "public_order_id", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     false},
    {FieldCode::kFortsTradeReplOrdersLogSessId, "sess_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsTradeReplOrdersLogIsinId, "isin_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsTradeReplOrdersLogPublicAmount, "public_amount", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     false},
    {FieldCode::kFortsTradeReplOrdersLogPublicAmountRest, "public_amount_rest", "i8", ValueClass::kSignedInteger, 8, 0,
     0, false},
    {FieldCode::kFortsTradeReplOrdersLogIdDeal, "id_deal", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsTradeReplOrdersLogXstatus, "xstatus", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsTradeReplOrdersLogXstatus2, "xstatus2", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsTradeReplOrdersLogPrice, "price", "d16.5", ValueClass::kDecimal, 0, 16, 5, false},
    {FieldCode::kFortsTradeReplOrdersLogMoment, "moment", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsTradeReplOrdersLogMomentNs, "moment_ns", "u8", ValueClass::kUnsignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsTradeReplOrdersLogDir, "dir", "i1", ValueClass::kSignedInteger, 1, 0, 0, false},
    {FieldCode::kFortsTradeReplOrdersLogPublicAction, "public_action", "i1", ValueClass::kSignedInteger, 1, 0, 0,
     false},
    {FieldCode::kFortsTradeReplOrdersLogClientCode, "client_code", "c7", ValueClass::kFixedString, 8, 0, 0, false},
    {FieldCode::kFortsTradeReplOrdersLogLoginFrom, "login_from", "c20", ValueClass::kFixedString, 21, 0, 0, false},
    {FieldCode::kFortsTradeReplOrdersLogComment, "comment", "c20", ValueClass::kFixedString, 21, 0, 0, false},
    {FieldCode::kFortsTradeReplOrdersLogExtId, "ext_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsTradeReplOrdersLogIdOrd1, "id_ord1", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsTradeReplOrdersLogPrevorderId, "prevorder_id", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsTradeReplOrdersLogPrivateOrderId, "private_order_id", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     false},
    {FieldCode::kFortsTradeReplOrdersLogPrivateAmount, "private_amount", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     false},
    {FieldCode::kFortsTradeReplOrdersLogPrivateAmountRest, "private_amount_rest", "i8", ValueClass::kSignedInteger, 8,
     0, 0, false},
    {FieldCode::kFortsTradeReplOrdersLogPrivateAction, "private_action", "i1", ValueClass::kSignedInteger, 1, 0, 0,
     false},
    {FieldCode::kFortsTradeReplUserDealReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsTradeReplUserDealReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsTradeReplUserDealReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsTradeReplUserDealSessId, "sess_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsTradeReplUserDealIsinId, "isin_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsTradeReplUserDealIdDeal, "id_deal", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsTradeReplUserDealXpos, "xpos", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsTradeReplUserDealXamount, "xamount", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsTradeReplUserDealPublicOrderIdBuy, "public_order_id_buy", "i8", ValueClass::kSignedInteger, 8, 0,
     0, false},
    {FieldCode::kFortsTradeReplUserDealPublicOrderIdSell, "public_order_id_sell", "i8", ValueClass::kSignedInteger, 8,
     0, 0, false},
    {FieldCode::kFortsTradeReplUserDealPrice, "price", "d16.5", ValueClass::kDecimal, 0, 16, 5, false},
    {FieldCode::kFortsTradeReplUserDealMoment, "moment", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsTradeReplUserDealMomentNs, "moment_ns", "u8", ValueClass::kUnsignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsTradeReplUserDealExtIdBuy, "ext_id_buy", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsTradeReplUserDealExtIdSell, "ext_id_sell", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsTradeReplUserDealCodeBuy, "code_buy", "c7", ValueClass::kFixedString, 8, 0, 0, false},
    {FieldCode::kFortsTradeReplUserDealCodeSell, "code_sell", "c7", ValueClass::kFixedString, 8, 0, 0, false},
    {FieldCode::kFortsTradeReplUserDealCommentBuy, "comment_buy", "c20", ValueClass::kFixedString, 21, 0, 0, false},
    {FieldCode::kFortsTradeReplUserDealCommentSell, "comment_sell", "c20", ValueClass::kFixedString, 21, 0, 0, false},
    {FieldCode::kFortsTradeReplUserDealLoginBuy, "login_buy", "c20", ValueClass::kFixedString, 21, 0, 0, false},
    {FieldCode::kFortsTradeReplUserDealLoginSell, "login_sell", "c20", ValueClass::kFixedString, 21, 0, 0, false},
    {FieldCode::kFortsTradeReplUserDealPrivateOrderIdBuy, "private_order_id_buy", "i8", ValueClass::kSignedInteger, 8,
     0, 0, false},
    {FieldCode::kFortsTradeReplUserDealPrivateOrderIdSell, "private_order_id_sell", "i8", ValueClass::kSignedInteger, 8,
     0, 0, false},
    {FieldCode::kFortsTradeReplHeartbeatReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsTradeReplHeartbeatReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsTradeReplHeartbeatReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsTradeReplHeartbeatServerTime, "server_time", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsTradeReplSysEventsReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsTradeReplSysEventsReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsTradeReplSysEventsReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsTradeReplSysEventsEventId, "event_id", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsTradeReplSysEventsSessId, "sess_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsTradeReplSysEventsEventType, "event_type", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsTradeReplSysEventsMessage, "message", "c64", ValueClass::kFixedString, 65, 0, 0, false},
    {FieldCode::kFortsTradeReplSysEventsServerTime, "server_time", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsDealsReplDealReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsDealsReplDealReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsDealsReplDealReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsDealsReplDealSessId, "sess_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsDealsReplDealIsinId, "isin_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsDealsReplDealIdDeal, "id_deal", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsDealsReplDealXpos, "xpos", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsDealsReplDealXamount, "xamount", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsDealsReplDealPublicOrderIdBuy, "public_order_id_buy", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     false},
    {FieldCode::kFortsDealsReplDealPublicOrderIdSell, "public_order_id_sell", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     false},
    {FieldCode::kFortsDealsReplDealPrice, "price", "d16.5", ValueClass::kDecimal, 0, 16, 5, false},
    {FieldCode::kFortsDealsReplDealMoment, "moment", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsDealsReplDealMomentNs, "moment_ns", "u8", ValueClass::kUnsignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsDealsReplDealNosystem, "nosystem", "i1", ValueClass::kSignedInteger, 1, 0, 0, false},
    {FieldCode::kFortsDealsReplDealXstatusBuy, "xstatus_buy", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsDealsReplDealXstatusSell, "xstatus_sell", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsDealsReplDealXstatus2Buy, "xstatus2_buy", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsDealsReplDealXstatus2Sell, "xstatus2_sell", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsDealsReplMultilegDealReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsDealsReplMultilegDealReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsDealsReplMultilegDealReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsDealsReplMultilegDealSessId, "sess_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsDealsReplMultilegDealIsinId, "isin_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsDealsReplMultilegDealIdDeal, "id_deal", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsDealsReplMultilegDealPublicOrderIdBuy, "public_order_id_buy", "i8", ValueClass::kSignedInteger, 8,
     0, 0, false},
    {FieldCode::kFortsDealsReplMultilegDealPublicOrderIdSell, "public_order_id_sell", "i8", ValueClass::kSignedInteger,
     8, 0, 0, false},
    {FieldCode::kFortsDealsReplMultilegDealXamount, "xamount", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsDealsReplMultilegDealPrice, "price", "d16.5", ValueClass::kDecimal, 0, 16, 5, false},
    {FieldCode::kFortsDealsReplHeartbeatReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsDealsReplHeartbeatReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsDealsReplHeartbeatReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsDealsReplSysEventsReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsDealsReplSysEventsReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsDealsReplSysEventsReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsDealsReplSysEventsSessId, "sess_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsDealsReplSysEventsEventType, "event_type", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplOrdersReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsUserorderbookReplOrdersReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsUserorderbookReplOrdersReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsUserorderbookReplOrdersPublicOrderId, "public_order_id", "i8", ValueClass::kSignedInteger, 8, 0,
     0, false},
    {FieldCode::kFortsUserorderbookReplOrdersSessId, "sess_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplOrdersClientCode, "client_code", "c7", ValueClass::kFixedString, 8, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplOrdersMoment, "moment", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplOrdersMomentNs, "moment_ns", "u8", ValueClass::kUnsignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplOrdersXstatus, "xstatus", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplOrdersXstatus2, "xstatus2", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplOrdersPublicAction, "public_action", "i1", ValueClass::kSignedInteger, 1, 0, 0,
     false},
    {FieldCode::kFortsUserorderbookReplOrdersIsinId, "isin_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplOrdersDir, "dir", "i1", ValueClass::kSignedInteger, 1, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplOrdersPrice, "price", "d16.5", ValueClass::kDecimal, 0, 16, 5, false},
    {FieldCode::kFortsUserorderbookReplOrdersPublicAmount, "public_amount", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     false},
    {FieldCode::kFortsUserorderbookReplOrdersPublicAmountRest, "public_amount_rest", "i8", ValueClass::kSignedInteger,
     8, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplOrdersComment, "comment", "c20", ValueClass::kFixedString, 21, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplOrdersExtId, "ext_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplOrdersLoginFrom, "login_from", "c20", ValueClass::kFixedString, 21, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplOrdersIdOrd1, "id_ord1", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplOrdersPrivateOrderId, "private_order_id", "i8", ValueClass::kSignedInteger, 8, 0,
     0, false},
    {FieldCode::kFortsUserorderbookReplOrdersPrivateAmount, "private_amount", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     false},
    {FieldCode::kFortsUserorderbookReplOrdersPrivateAmountRest, "private_amount_rest", "i8", ValueClass::kSignedInteger,
     8, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplOrdersPrivateAction, "private_action", "i1", ValueClass::kSignedInteger, 1, 0, 0,
     false},
    {FieldCode::kFortsUserorderbookReplInfoReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsUserorderbookReplInfoReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsUserorderbookReplInfoReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsUserorderbookReplInfoMoment, "moment", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplInfoPublicationState, "publication_state", "i1", ValueClass::kSignedInteger, 1,
     0, 0, false},
    {FieldCode::kFortsUserorderbookReplInfoTradesRev, "trades_rev", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsUserorderbookReplInfoTradesLifenum, "trades_lifenum", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     false},
    {FieldCode::kFortsAggrReplOrdersAggrReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsAggrReplOrdersAggrReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsAggrReplOrdersAggrReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsAggrReplOrdersAggrIsinId, "isin_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsAggrReplOrdersAggrPrice, "price", "d16.5", ValueClass::kDecimal, 0, 16, 5, false},
    {FieldCode::kFortsAggrReplOrdersAggrVolume, "volume", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsAggrReplOrdersAggrMoment, "moment", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsAggrReplOrdersAggrMomentNs, "moment_ns", "u8", ValueClass::kUnsignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsAggrReplOrdersAggrDir, "dir", "i1", ValueClass::kSignedInteger, 1, 0, 0, false},
    {FieldCode::kFortsAggrReplOrdersAggrSynthVolume, "synth_volume", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsAggrReplSysEventsReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsAggrReplSysEventsReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsAggrReplSysEventsReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsAggrReplSysEventsEventType, "event_type", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsAggrReplSysEventsEventId, "event_id", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsAggrReplSysEventsSessId, "sess_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsAggrReplSysEventsMessage, "message", "c64", ValueClass::kFixedString, 65, 0, 0, false},
    {FieldCode::kFortsAggrReplSysEventsServerTime, "server_time", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsPosReplPositionReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsPosReplPositionReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsPosReplPositionReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsPosReplPositionClientCode, "client_code", "c7", ValueClass::kFixedString, 8, 0, 0, false},
    {FieldCode::kFortsPosReplPositionIsinId, "isin_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsPosReplPositionXpos, "xpos", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsPosReplPositionXbuysQty, "xbuys_qty", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsPosReplPositionXsellsQty, "xsells_qty", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsPosReplPositionXdayOpenQty, "xday_open_qty", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsPosReplPositionXdayOpenBuysQty, "xday_open_buys_qty", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     false},
    {FieldCode::kFortsPosReplPositionXdayOpenSellsQty, "xday_open_sells_qty", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     false},
    {FieldCode::kFortsPosReplPositionXopenQty, "xopen_qty", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsPosReplPositionWaprice, "waprice", "d16.5", ValueClass::kDecimal, 0, 16, 5, false},
    {FieldCode::kFortsPosReplPositionNetVolumeRur, "net_volume_rur", "d26.2", ValueClass::kDecimal, 0, 26, 2, false},
    {FieldCode::kFortsPosReplPositionLastDealId, "last_deal_id", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsPosReplPositionLastQuantity, "last_quantity", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsPosReplPositionAccountType, "account_type", "i1", ValueClass::kSignedInteger, 1, 0, 0, false},
    {FieldCode::kFortsPosReplInfoReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsPosReplInfoReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsPosReplInfoReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsPosReplInfoTradesRev, "trades_rev", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsPosReplInfoTradesLifenum, "trades_lifenum", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsPosReplInfoServerTime, "server_time", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsPartReplSysEventsReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsPartReplSysEventsReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsPartReplSysEventsReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsPartReplSysEventsEventType, "event_type", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsPartReplSysEventsEventId, "event_id", "i8", ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsPartReplSysEventsSessId, "sess_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsPartReplSysEventsMessage, "message", "c64", ValueClass::kFixedString, 65, 0, 0, false},
    {FieldCode::kFortsPartReplSysEventsServerTime, "server_time", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsRefdataReplFutSessContentsReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsRefdataReplFutSessContentsReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsRefdataReplFutSessContentsReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsRefdataReplFutSessContentsSessId, "sess_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsRefdataReplFutSessContentsIsinId, "isin_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsRefdataReplFutSessContentsShortIsin, "short_isin", "c25", ValueClass::kFixedString, 26, 0, 0,
     false},
    {FieldCode::kFortsRefdataReplFutSessContentsIsin, "isin", "c25", ValueClass::kFixedString, 26, 0, 0, false},
    {FieldCode::kFortsRefdataReplFutSessContentsName, "name", "c75", ValueClass::kFixedString, 76, 0, 0, false},
    {FieldCode::kFortsRefdataReplFutSessContentsInstTerm, "inst_term", "i4", ValueClass::kSignedInteger, 4, 0, 0,
     false},
    {FieldCode::kFortsRefdataReplFutSessContentsBaseContractCode, "base_contract_code", "c25", ValueClass::kFixedString,
     26, 0, 0, false},
    {FieldCode::kFortsRefdataReplFutSessContentsLimitUp, "limit_up", "d16.5", ValueClass::kDecimal, 0, 16, 5, false},
    {FieldCode::kFortsRefdataReplFutSessContentsLimitDown, "limit_down", "d16.5", ValueClass::kDecimal, 0, 16, 5,
     false},
    {FieldCode::kFortsRefdataReplFutSessContentsSettlementPriceOpen, "settlement_price_open", "d16.5",
     ValueClass::kDecimal, 0, 16, 5, false},
    {FieldCode::kFortsRefdataReplFutSessContentsRoundto, "roundto", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsRefdataReplFutSessContentsMinStep, "min_step", "d16.5", ValueClass::kDecimal, 0, 16, 5, false},
    {FieldCode::kFortsRefdataReplFutSessContentsLotVolume, "lot_volume", "i4", ValueClass::kSignedInteger, 4, 0, 0,
     false},
    {FieldCode::kFortsRefdataReplFutSessContentsStepPrice, "step_price", "d16.5", ValueClass::kDecimal, 0, 16, 5,
     false},
    {FieldCode::kFortsRefdataReplFutSessContentsLastTradeDate, "last_trade_date", "t", ValueClass::kTimestamp, 0, 0, 0,
     false},
    {FieldCode::kFortsRefdataReplFutSessContentsIsSpread, "is_spread", "i1", ValueClass::kSignedInteger, 1, 0, 0,
     false},
    {FieldCode::kFortsRefdataReplFutSessContentsSettlementPrice, "settlement_price", "d16.5", ValueClass::kDecimal, 0,
     16, 5, false},
    {FieldCode::kFortsRefdataReplFutSessContentsSigns, "signs", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsRefdataReplFutSessContentsState, "state", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsRefdataReplFutSessContentsStepPriceCurr, "step_price_curr", "d16.5", ValueClass::kDecimal, 0, 16,
     5, false},
    {FieldCode::kFortsRefdataReplFutSessContentsTradeModeId, "trade_mode_id", "i4", ValueClass::kSignedInteger, 4, 0, 0,
     false},
    {FieldCode::kFortsRefdataReplFutSessContentsGroupMask, "group_mask", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     false},
    {FieldCode::kFortsRefdataReplFutSessContentsTradePeriodAccess, "trade_period_access", "i8",
     ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsRefdataReplFutVcbReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsRefdataReplFutVcbReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsRefdataReplFutVcbReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsRefdataReplFutVcbBaseContractCode, "base_contract_code", "c25", ValueClass::kFixedString, 26, 0,
     0, false},
    {FieldCode::kFortsRefdataReplFutVcbCurr, "curr", "c3", ValueClass::kFixedString, 4, 0, 0, false},
    {FieldCode::kFortsRefdataReplFutVcbBaseContractId, "base_contract_id", "i4", ValueClass::kSignedInteger, 4, 0, 0,
     false},
    {FieldCode::kFortsRefdataReplFutVcbBoardMd, "board_md", "c4", ValueClass::kFixedString, 5, 0, 0, false},
    {FieldCode::kFortsRefdataReplFutInstrumentsReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsRefdataReplFutInstrumentsReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsRefdataReplFutInstrumentsReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsRefdataReplFutInstrumentsIsinId, "isin_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsRefdataReplFutInstrumentsShortIsin, "short_isin", "c25", ValueClass::kFixedString, 26, 0, 0,
     false},
    {FieldCode::kFortsRefdataReplFutInstrumentsIsin, "isin", "c25", ValueClass::kFixedString, 26, 0, 0, false},
    {FieldCode::kFortsRefdataReplFutInstrumentsName, "name", "c75", ValueClass::kFixedString, 76, 0, 0, false},
    {FieldCode::kFortsRefdataReplFutInstrumentsInstTerm, "inst_term", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsRefdataReplFutInstrumentsBaseContractCode, "base_contract_code", "c25", ValueClass::kFixedString,
     26, 0, 0, false},
    {FieldCode::kFortsRefdataReplFutInstrumentsRoundto, "roundto", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsRefdataReplFutInstrumentsMinStep, "min_step", "d16.5", ValueClass::kDecimal, 0, 16, 5, false},
    {FieldCode::kFortsRefdataReplFutInstrumentsLotVolume, "lot_volume", "i4", ValueClass::kSignedInteger, 4, 0, 0,
     false},
    {FieldCode::kFortsRefdataReplFutInstrumentsStepPrice, "step_price", "d16.5", ValueClass::kDecimal, 0, 16, 5, false},
    {FieldCode::kFortsRefdataReplFutInstrumentsLastTradeDate, "last_trade_date", "t", ValueClass::kTimestamp, 0, 0, 0,
     false},
    {FieldCode::kFortsRefdataReplFutInstrumentsIsSpread, "is_spread", "i1", ValueClass::kSignedInteger, 1, 0, 0, false},
    {FieldCode::kFortsRefdataReplFutInstrumentsSettlementPrice, "settlement_price", "d16.5", ValueClass::kDecimal, 0,
     16, 5, false},
    {FieldCode::kFortsRefdataReplFutInstrumentsSigns, "signs", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsRefdataReplFutInstrumentsStepPriceCurr, "step_price_curr", "d16.5", ValueClass::kDecimal, 0, 16,
     5, false},
    {FieldCode::kFortsRefdataReplFutInstrumentsTradeModeId, "trade_mode_id", "i4", ValueClass::kSignedInteger, 4, 0, 0,
     false},
    {FieldCode::kFortsRefdataReplFutInstrumentsGroupMask, "group_mask", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     false},
    {FieldCode::kFortsRefdataReplFutInstrumentsTradePeriodAccess, "trade_period_access", "i8",
     ValueClass::kSignedInteger, 8, 0, 0, false},
    {FieldCode::kFortsRefdataReplSysMessagesReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsRefdataReplSysMessagesReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsRefdataReplSysMessagesReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsRefdataReplSysMessagesMsgId, "msg_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsRefdataReplSysMessagesLangCode, "lang_code", "c8", ValueClass::kFixedString, 9, 0, 0, false},
    {FieldCode::kFortsRefdataReplSysMessagesTypeId, "type_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsRefdataReplSysMessagesMoment, "moment", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsRefdataReplSysMessagesText, "text", "c255", ValueClass::kFixedString, 256, 0, 0, false},
    {FieldCode::kFortsRefdataReplSysMessagesUrgency, "urgency", "i1", ValueClass::kSignedInteger, 1, 0, 0, false},
    {FieldCode::kFortsRefdataReplSysMessagesStatus, "status", "i1", ValueClass::kSignedInteger, 1, 0, 0, false},
    {FieldCode::kFortsRefdataReplSysMessagesMessageBody, "message_body", "c4000", ValueClass::kFixedString, 4001, 0, 0,
     false},
    {FieldCode::kFortsRefdataReplSessionReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsRefdataReplSessionReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsRefdataReplSessionReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsRefdataReplSessionSessId, "sess_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsRefdataReplSessionBegin, "begin", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsRefdataReplSessionEnd, "end", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsRefdataReplSessionState, "state", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsRefdataReplSessionInterClBegin, "inter_cl_begin", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsRefdataReplSessionInterClEnd, "inter_cl_end", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsRefdataReplSessionInterClState, "inter_cl_state", "i4", ValueClass::kSignedInteger, 4, 0, 0,
     false},
    {FieldCode::kFortsRefdataReplSessionEveOn, "eve_on", "i1", ValueClass::kSignedInteger, 1, 0, 0, false},
    {FieldCode::kFortsRefdataReplSessionEveBegin, "eve_begin", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsRefdataReplSessionEveEnd, "eve_end", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsRefdataReplSessionMonOn, "mon_on", "i1", ValueClass::kSignedInteger, 1, 0, 0, false},
    {FieldCode::kFortsRefdataReplSessionMonBegin, "mon_begin", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsRefdataReplSessionMonEnd, "mon_end", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsRefdataReplSessionSettlSessBegin, "settl_sess_begin", "t", ValueClass::kTimestamp, 0, 0, 0,
     false},
    {FieldCode::kFortsRefdataReplSessionClrSessBegin, "clr_sess_begin", "t", ValueClass::kTimestamp, 0, 0, 0, false},
    {FieldCode::kFortsRefdataReplSessionSettlPriceCalcTime, "settl_price_calc_time", "t", ValueClass::kTimestamp, 0, 0,
     0, false},
    {FieldCode::kFortsRefdataReplSessionSettlSessT1Begin, "settl_sess_t1_begin", "t", ValueClass::kTimestamp, 0, 0, 0,
     false},
    {FieldCode::kFortsRefdataReplSessionMarginCallFixSchedule, "margin_call_fix_schedule", "t", ValueClass::kTimestamp,
     0, 0, 0, false},
    {FieldCode::kFortsSessionstateReplSessionStateReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsSessionstateReplSessionStateReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsSessionstateReplSessionStateReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0, true},
    {FieldCode::kFortsSessionstateReplSessionStateSessId, "sess_id", "i4", ValueClass::kSignedInteger, 4, 0, 0, false},
    {FieldCode::kFortsSessionstateReplSessionStatePublicState, "public_state", "i4", ValueClass::kSignedInteger, 4, 0,
     0, false},
    {FieldCode::kFortsInstrumentstateReplInstrumentStateReplId, "replID", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     true},
    {FieldCode::kFortsInstrumentstateReplInstrumentStateReplRev, "replRev", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     true},
    {FieldCode::kFortsInstrumentstateReplInstrumentStateReplAct, "replAct", "i8", ValueClass::kSignedInteger, 8, 0, 0,
     true},
    {FieldCode::kFortsInstrumentstateReplInstrumentStateIsinId, "isin_id", "i4", ValueClass::kSignedInteger, 4, 0, 0,
     false},
    {FieldCode::kFortsInstrumentstateReplInstrumentStatePublicState, "public_state", "i4", ValueClass::kSignedInteger,
     4, 0, 0, false},
}};

} // namespace

std::span<const TypeDescriptor> TypeDescriptors() {
    return kTypeDescriptors;
}

std::span<const StreamDescriptor> StreamDescriptors() {
    return kStreamDescriptors;
}

std::span<const TableDescriptor> TableDescriptors() {
    return kTableDescriptors;
}

std::span<const FieldDescriptor> FieldDescriptors() {
    return kFieldDescriptors;
}

const TypeDescriptor* FindTypeByToken(std::string_view type_token) {
    for (const auto& descriptor : kTypeDescriptors) {
        if (descriptor.type_token == type_token) {
            return &descriptor;
        }
    }
    return nullptr;
}

const StreamDescriptor* FindStreamByCode(StreamCode stream_code) {
    for (const auto& descriptor : kStreamDescriptors) {
        if (descriptor.stream_code == stream_code) {
            return &descriptor;
        }
    }
    return nullptr;
}

const TableDescriptor* FindTableByCode(TableCode table_code) {
    for (const auto& descriptor : kTableDescriptors) {
        if (descriptor.table_code == table_code) {
            return &descriptor;
        }
    }
    return nullptr;
}

const FieldDescriptor* FindFieldByCode(FieldCode field_code) {
    for (const auto& descriptor : kFieldDescriptors) {
        if (descriptor.field_code == field_code) {
            return &descriptor;
        }
    }
    return nullptr;
}

std::span<const TableDescriptor> TablesForStream(StreamCode stream_code) {
    const auto* stream = FindStreamByCode(stream_code);
    if (stream == nullptr) {
        return {};
    }
    return std::span<const TableDescriptor>(kTableDescriptors.data() + stream->first_table_index, stream->table_count);
}

std::span<const FieldDescriptor> FieldsForTable(TableCode table_code) {
    const auto* table = FindTableByCode(table_code);
    if (table == nullptr) {
        return {};
    }
    return std::span<const FieldDescriptor>(kFieldDescriptors.data() + table->first_field_index, table->field_count);
}

} // namespace moex::plaza2::generated
