#pragma once

// CGate 9.9 fields consumed by the retained product streams.
// Native negotiated descriptors determine offsets; additional server fields are accepted.

#include <cstddef>
#include <cstdint>
#include <span>
#include <string_view>

namespace moex::plaza2::generated {

enum class ValueClass : std::uint8_t {
    kSignedInteger = 0,
    kUnsignedInteger = 1,
    kFixedString = 2,
    kDecimal = 3,
    kFloatingPoint = 4,
    kTimestamp = 5,
    kBinary = 6,
};

enum class StreamCode : std::uint32_t {
    kFortsTradeRepl = 0x7344FBC6u,
    kFortsDealsRepl = 0x271473DDu,
    kFortsUserorderbookRepl = 0x9854831Cu,
    kFortsAggrRepl = 0x20C18715u,
    kFortsPosRepl = 0x1E3EE282u,
    kFortsPartRepl = 0x29343FB7u,
    kFortsRefdataRepl = 0xF42AF31Fu,
    kFortsSessionstateRepl = 0x4C6EE2C3u,
    kFortsInstrumentstateRepl = 0x53AD8B6Au,
};

enum class TableCode : std::uint32_t {
    kFortsTradeReplOrdersLog = 0xAF577B88u,
    kFortsTradeReplMultilegOrdersLog = 0x73C1DC30u,
    kFortsTradeReplUserDeal = 0xF08A3A2Au,
    kFortsTradeReplUserMultilegDeal = 0x61EE4E6Au,
    kFortsTradeReplHeartbeat = 0x979DC238u,
    kFortsTradeReplSysEvents = 0xFB39C3DFu,
    kFortsDealsReplDeal = 0x82D36C4Fu,
    kFortsDealsReplMultilegDeal = 0x1F3DCD1Du,
    kFortsDealsReplHeartbeat = 0xA7E429D7u,
    kFortsDealsReplSysEvents = 0xF5D02ADEu,
    kFortsUserorderbookReplOrders = 0x105CE01Bu,
    kFortsUserorderbookReplMultilegOrders = 0x863FAFA7u,
    kFortsUserorderbookReplInfo = 0x918EB8CAu,
    kFortsUserorderbookReplOrdersCurrentday = 0xA45BBA41u,
    kFortsUserorderbookReplMultilegOrdersCurrentday = 0x83251B05u,
    kFortsUserorderbookReplInfoCurrentday = 0x88A348EAu,
    kFortsAggrReplOrdersAggr = 0x2EB6A868u,
    kFortsAggrReplSysEvents = 0x4F557DAAu,
    kFortsPosReplPosition = 0x52EE9DE3u,
    kFortsPosReplPositionSa = 0x930D20ECu,
    kFortsPosReplInfo = 0xAD7C9EFCu,
    kFortsPartReplPart = 0xA6FD7DBAu,
    kFortsPartReplPartSa = 0x4AEB6E5Fu,
    kFortsPartReplSysEvents = 0xDD09E198u,
    kFortsRefdataReplFutSessContents = 0xB1E3BBC0u,
    kFortsRefdataReplFutVcb = 0x70275D16u,
    kFortsRefdataReplFutInstruments = 0x74A0DBCBu,
    kFortsRefdataReplSysMessages = 0x593104F1u,
    kFortsRefdataReplOptSessContents = 0x719A3C1Au,
    kFortsRefdataReplMultilegDict = 0x785AFD8Du,
    kFortsRefdataReplInstr2matchingMap = 0x0C0D31D5u,
    kFortsRefdataReplSession = 0xD83DB291u,
    kFortsSessionstateReplSessionState = 0xC76B56A7u,
    kFortsInstrumentstateReplInstrumentState = 0xED3612BBu,
    kFortsInstrumentstateReplSysEvents = 0xFBFFE27Du,
};

enum class FieldCode : std::uint32_t {
    kFortsInstrumentstateReplSysEventsReplId = 0x238D77B5u,
    kFortsInstrumentstateReplSysEventsReplRev = 0xD288D2A4u,
    kFortsInstrumentstateReplSysEventsReplAct = 0x96112BC4u,
    kFortsInstrumentstateReplSysEventsEventId = 0x744B99A4u,
    kFortsInstrumentstateReplSysEventsSessId = 0x2B37C451u,
    kFortsInstrumentstateReplSysEventsEventType = 0x729A06CEu,
    kFortsInstrumentstateReplSysEventsMessage = 0xE144F36Cu,
    kFortsInstrumentstateReplSysEventsServerTime = 0xEEE85693u,

    kFortsTradeReplOrdersLogReplId = 0x9966AC1Cu,
    kFortsTradeReplOrdersLogReplRev = 0xC52EBF1Eu,
    kFortsTradeReplOrdersLogReplAct = 0x3CE6481Fu,
    kFortsTradeReplOrdersLogPublicOrderId = 0x7844B3F6u,
    kFortsTradeReplOrdersLogSessId = 0x7DE5FB9Eu,
    kFortsTradeReplOrdersLogIsinId = 0x9CC7DE39u,
    kFortsTradeReplOrdersLogPublicAmount = 0x64BDB612u,
    kFortsTradeReplOrdersLogPublicAmountRest = 0x79CC5A49u,
    kFortsTradeReplOrdersLogIdDeal = 0x6D2E69F0u,
    kFortsTradeReplOrdersLogXstatus = 0x120F545Eu,
    kFortsTradeReplOrdersLogXstatus2 = 0xDA21E604u,
    kFortsTradeReplOrdersLogPrice = 0x885DB8D1u,
    kFortsTradeReplOrdersLogMoment = 0x128D4B50u,
    kFortsTradeReplOrdersLogMomentNs = 0x82304B8Eu,
    kFortsTradeReplOrdersLogDir = 0x0489B15Bu,
    kFortsTradeReplOrdersLogPublicAction = 0x9D049AE4u,
    kFortsTradeReplOrdersLogClientCode = 0x84477BB1u,
    kFortsTradeReplOrdersLogLoginFrom = 0xC6C134B6u,
    kFortsTradeReplOrdersLogComment = 0x5FF4C251u,
    kFortsTradeReplOrdersLogExtId = 0x2692C5DDu,
    kFortsTradeReplOrdersLogIdOrd1 = 0xE003C3F0u,
    kFortsTradeReplOrdersLogPrevorderId = 0x2672335Fu,
    kFortsTradeReplOrdersLogPrivateOrderId = 0xE9654BC0u,
    kFortsTradeReplOrdersLogPrivateAmount = 0xB5C7545Cu,
    kFortsTradeReplOrdersLogPrivateAmountRest = 0xB4385B6Bu,
    kFortsTradeReplOrdersLogPrivateAction = 0x9B3918DAu,
    kFortsTradeReplMultilegOrdersLogReplId = 0xE5178344u,
    kFortsTradeReplMultilegOrdersLogReplRev = 0xE7630E26u,
    kFortsTradeReplMultilegOrdersLogReplAct = 0x7F1AC987u,
    kFortsTradeReplMultilegOrdersLogPublicOrderId = 0x5437732Eu,
    kFortsTradeReplMultilegOrdersLogSessId = 0x9C09C5D6u,
    kFortsTradeReplMultilegOrdersLogIsinId = 0x461D30E1u,
    kFortsTradeReplMultilegOrdersLogPublicAmount = 0x0FA5866Au,
    kFortsTradeReplMultilegOrdersLogPublicAmountRest = 0x374191A1u,
    kFortsTradeReplMultilegOrdersLogIdDeal = 0xEDCC4658u,
    kFortsTradeReplMultilegOrdersLogXstatus = 0x14DB2C66u,
    kFortsTradeReplMultilegOrdersLogXstatus2 = 0x2906C83Cu,
    kFortsTradeReplMultilegOrdersLogPrice = 0x3C4A4939u,
    kFortsTradeReplMultilegOrdersLogMoment = 0xA437E1F8u,
    kFortsTradeReplMultilegOrdersLogMomentNs = 0xD1518E06u,
    kFortsTradeReplMultilegOrdersLogDir = 0x20B016C3u,
    kFortsTradeReplMultilegOrdersLogPublicAction = 0xC29910FCu,
    kFortsTradeReplMultilegOrdersLogClientCode = 0xE1F57A39u,
    kFortsTradeReplMultilegOrdersLogLoginFrom = 0x5961716Eu,
    kFortsTradeReplMultilegOrdersLogComment = 0xA0A0B469u,
    kFortsTradeReplMultilegOrdersLogExtId = 0xDC102015u,
    kFortsTradeReplMultilegOrdersLogIdOrd1 = 0x43C20598u,
    kFortsTradeReplMultilegOrdersLogPrivateOrderId = 0x31282E78u,
    kFortsTradeReplMultilegOrdersLogPrivateAmount = 0x0FC4B3B4u,
    kFortsTradeReplMultilegOrdersLogPrivateAmountRest = 0x551F9A43u,
    kFortsTradeReplMultilegOrdersLogPrivateAction = 0x5DE6A392u,
    kFortsTradeReplUserDealReplId = 0xE4827496u,
    kFortsTradeReplUserDealReplRev = 0xD3C6C534u,
    kFortsTradeReplUserDealReplAct = 0x044B5779u,
    kFortsTradeReplUserDealSessId = 0x01D72400u,
    kFortsTradeReplUserDealIsinId = 0xE7C87D47u,
    kFortsTradeReplUserDealIdDeal = 0xF5BE3C5Eu,
    kFortsTradeReplUserDealXpos = 0x95C1DEECu,
    kFortsTradeReplUserDealXamount = 0xC7888CDAu,
    kFortsTradeReplUserDealPublicOrderIdBuy = 0x95B98E3Fu,
    kFortsTradeReplUserDealPublicOrderIdSell = 0x153F1021u,
    kFortsTradeReplUserDealPrice = 0x864EFA3Bu,
    kFortsTradeReplUserDealMoment = 0x7EBB0E2Eu,
    kFortsTradeReplUserDealMomentNs = 0x0B9669CCu,
    kFortsTradeReplUserDealExtIdBuy = 0xEAF80908u,
    kFortsTradeReplUserDealExtIdSell = 0x904160D4u,
    kFortsTradeReplUserDealCodeBuy = 0x5247CC88u,
    kFortsTradeReplUserDealCodeSell = 0xB2D22354u,
    kFortsTradeReplUserDealCommentBuy = 0xA425FB98u,
    kFortsTradeReplUserDealCommentSell = 0x481ED764u,
    kFortsTradeReplUserDealLoginBuy = 0x23563420u,
    kFortsTradeReplUserDealLoginSell = 0x98A76D0Cu,
    kFortsTradeReplUserDealPrivateOrderIdBuy = 0x76BD7A65u,
    kFortsTradeReplUserDealPrivateOrderIdSell = 0x6DD745BBu,
    kFortsTradeReplUserMultilegDealReplId = 0x07621AB6u,
    kFortsTradeReplUserMultilegDealReplRev = 0x9BB3EA14u,
    kFortsTradeReplUserMultilegDealReplAct = 0xCC3A0F59u,
    kFortsTradeReplUserMultilegDealSessId = 0x3D1F8160u,
    kFortsTradeReplUserMultilegDealIsinId = 0x086DDF27u,
    kFortsTradeReplUserMultilegDealIdDeal = 0x9001EA3Eu,
    kFortsTradeReplUserMultilegDealPublicOrderIdBuy = 0x664C539Fu,
    kFortsTradeReplUserMultilegDealPublicOrderIdSell = 0x09D02F01u,
    kFortsTradeReplUserMultilegDealXamount = 0x5706DCFAu,
    kFortsTradeReplUserMultilegDealPrice = 0xC0A5605Bu,
    kFortsTradeReplUserMultilegDealRatePrice = 0xCEFE261Au,
    kFortsTradeReplUserMultilegDealSwapPrice = 0x97A467C7u,
    kFortsTradeReplUserMultilegDealMoment = 0x34BD6DCEu,
    kFortsTradeReplUserMultilegDealMomentNs = 0xFE2AA72Cu,
    kFortsTradeReplUserMultilegDealExtIdBuy = 0x54060BA8u,
    kFortsTradeReplUserMultilegDealExtIdSell = 0x3A7CD1F4u,
    kFortsTradeReplUserMultilegDealCodeBuy = 0x9B42EDE8u,
    kFortsTradeReplUserMultilegDealCodeSell = 0x1CDB5D34u,
    kFortsTradeReplUserMultilegDealCommentBuy = 0x05B62178u,
    kFortsTradeReplUserMultilegDealCommentSell = 0xE4BE26C4u,
    kFortsTradeReplUserMultilegDealLoginBuy = 0xF546DE00u,
    kFortsTradeReplUserMultilegDealLoginSell = 0x38FDA66Cu,
    kFortsTradeReplUserMultilegDealPrivateOrderIdBuy = 0x8EA06145u,
    kFortsTradeReplUserMultilegDealPrivateOrderIdSell = 0x0C41FF1Bu,
    kFortsTradeReplHeartbeatReplId = 0x6C53000Cu,
    kFortsTradeReplHeartbeatReplRev = 0x7D4A4D6Eu,
    kFortsTradeReplHeartbeatReplAct = 0x582BD1CFu,
    kFortsTradeReplHeartbeatServerTime = 0x4D3A4CF1u,
    kFortsTradeReplSysEventsReplId = 0x8C1AAF1Du,
    kFortsTradeReplSysEventsReplRev = 0xCCBCDDCDu,
    kFortsTradeReplSysEventsReplAct = 0x7EA7F4CCu,
    kFortsTradeReplSysEventsEventId = 0x1BECDD31u,
    kFortsTradeReplSysEventsSessId = 0xF5340DC5u,
    kFortsTradeReplSysEventsEventType = 0x1A7E39D4u,
    kFortsTradeReplSysEventsMessage = 0x263DC528u,
    kFortsTradeReplSysEventsServerTime = 0x500D7742u,
    kFortsDealsReplDealReplId = 0x8267BE3Du,
    kFortsDealsReplDealReplRev = 0x676D77ADu,
    kFortsDealsReplDealReplAct = 0x19588EACu,
    kFortsDealsReplDealSessId = 0x033E4D25u,
    kFortsDealsReplDealIsinId = 0x5F22E9EAu,
    kFortsDealsReplDealIdDeal = 0x87881BE3u,
    kFortsDealsReplDealXpos = 0x4898FDDBu,
    kFortsDealsReplDealXamount = 0x1B5119DFu,
    kFortsDealsReplDealPublicOrderIdBuy = 0x8CA83B9Au,
    kFortsDealsReplDealPublicOrderIdSell = 0x25FA035Au,
    kFortsDealsReplDealPrice = 0x50271D16u,
    kFortsDealsReplDealMoment = 0xAF64C489u,
    kFortsDealsReplDealMomentNs = 0x7295B435u,
    kFortsDealsReplDealNosystem = 0x576E7987u,
    kFortsDealsReplDealXstatusBuy = 0xAD3A8366u,
    kFortsDealsReplDealXstatusSell = 0x04AFE9AEu,
    kFortsDealsReplDealXstatus2Buy = 0x39DE0106u,
    kFortsDealsReplDealXstatus2Sell = 0xCA0E47CEu,
    kFortsDealsReplMultilegDealReplId = 0xAF51493Bu,
    kFortsDealsReplMultilegDealReplRev = 0x6AC9AC37u,
    kFortsDealsReplMultilegDealReplAct = 0xD27D1A72u,
    kFortsDealsReplMultilegDealSessId = 0xCA4D793Bu,
    kFortsDealsReplMultilegDealIsinId = 0xD7408FD4u,
    kFortsDealsReplMultilegDealIdDeal = 0xCD088A45u,
    kFortsDealsReplMultilegDealPublicOrderIdBuy = 0x80B629BCu,
    kFortsDealsReplMultilegDealPublicOrderIdSell = 0x2F842FF0u,
    kFortsDealsReplMultilegDealXamount = 0x9CBD6895u,
    kFortsDealsReplMultilegDealPrice = 0xC0323024u,
    kFortsDealsReplHeartbeatReplId = 0xDF548BD5u,
    kFortsDealsReplHeartbeatReplRev = 0xD7DCF005u,
    kFortsDealsReplHeartbeatReplAct = 0xA74DD064u,
    kFortsDealsReplSysEventsReplId = 0x763081F2u,
    kFortsDealsReplSysEventsReplRev = 0xBFB5BC80u,
    kFortsDealsReplSysEventsReplAct = 0x0DD532DDu,
    kFortsDealsReplSysEventsSessId = 0x554C7BE4u,
    kFortsDealsReplSysEventsEventType = 0xA54315A7u,
    kFortsUserorderbookReplOrdersReplId = 0x5A79E681u,
    kFortsUserorderbookReplOrdersReplRev = 0x187241A1u,
    kFortsUserorderbookReplOrdersReplAct = 0xD7CDEE18u,
    kFortsUserorderbookReplOrdersPublicOrderId = 0x72D56CE5u,
    kFortsUserorderbookReplOrdersSessId = 0x232C2141u,
    kFortsUserorderbookReplOrdersClientCode = 0x5A0F2FE2u,
    kFortsUserorderbookReplOrdersMoment = 0xF0A37055u,
    kFortsUserorderbookReplOrdersMomentNs = 0x1B60C0B9u,
    kFortsUserorderbookReplOrdersXstatus = 0x5A742C69u,
    kFortsUserorderbookReplOrdersXstatus2 = 0xBFE1D341u,
    kFortsUserorderbookReplOrdersPublicAction = 0xA28409DFu,
    kFortsUserorderbookReplOrdersIsinId = 0x63E2F466u,
    kFortsUserorderbookReplOrdersDir = 0xC8671AACu,
    kFortsUserorderbookReplOrdersPrice = 0x0BDDC082u,
    kFortsUserorderbookReplOrdersPublicAmount = 0xB9E01E29u,
    kFortsUserorderbookReplOrdersPublicAmountRest = 0x897B6DE0u,
    kFortsUserorderbookReplOrdersComment = 0x025D1AA6u,
    kFortsUserorderbookReplOrdersExtId = 0xCD76AC2Cu,
    kFortsUserorderbookReplOrdersLoginFrom = 0x132ED793u,
    kFortsUserorderbookReplOrdersIdOrd1 = 0x14F86853u,
    kFortsUserorderbookReplOrdersPrivateOrderId = 0x8DA28A89u,
    kFortsUserorderbookReplOrdersPrivateAmount = 0xFCAE4ECDu,
    kFortsUserorderbookReplOrdersPrivateAmountRest = 0x167E9274u,
    kFortsUserorderbookReplOrdersPrivateAction = 0x2F639ED3u,
    kFortsUserorderbookReplMultilegOrdersReplId = 0xD6683EE5u,
    kFortsUserorderbookReplMultilegOrdersReplRev = 0x1F099B35u,
    kFortsUserorderbookReplMultilegOrdersReplAct = 0x8BEFE3F4u,
    kFortsUserorderbookReplMultilegOrdersPublicOrderId = 0xC52682F9u,
    kFortsUserorderbookReplMultilegOrdersSessId = 0x7DA5E6FDu,
    kFortsUserorderbookReplMultilegOrdersClientCode = 0xB2AB7B36u,
    kFortsUserorderbookReplMultilegOrdersMoment = 0x9761B791u,
    kFortsUserorderbookReplMultilegOrdersMomentNs = 0x42DC080Du,
    kFortsUserorderbookReplMultilegOrdersXstatus = 0x821E01E5u,
    kFortsUserorderbookReplMultilegOrdersXstatus2 = 0xAC3CE575u,
    kFortsUserorderbookReplMultilegOrdersPublicAction = 0x07529983u,
    kFortsUserorderbookReplMultilegOrdersIsinId = 0xB52B6EB2u,
    kFortsUserorderbookReplMultilegOrdersDir = 0xF25585E8u,
    kFortsUserorderbookReplMultilegOrdersPrice = 0xAA11719Eu,
    kFortsUserorderbookReplMultilegOrdersPublicAmount = 0xD2DE2F5Du,
    kFortsUserorderbookReplMultilegOrdersPublicAmountRest = 0x7F69F224u,
    kFortsUserorderbookReplMultilegOrdersComment = 0x88F81CEAu,
    kFortsUserorderbookReplMultilegOrdersExtId = 0x5DB67CA8u,
    kFortsUserorderbookReplMultilegOrdersLoginFrom = 0x3550112Fu,
    kFortsUserorderbookReplMultilegOrdersIdOrd1 = 0xBBF3CCD7u,
    kFortsUserorderbookReplMultilegOrdersPrivateOrderId = 0x2E826F5Du,
    kFortsUserorderbookReplMultilegOrdersPrivateAmount = 0xB8FFD4A1u,
    kFortsUserorderbookReplMultilegOrdersPrivateAmountRest = 0xFA6D39D8u,
    kFortsUserorderbookReplMultilegOrdersPrivateAction = 0x78C6E417u,
    kFortsUserorderbookReplInfoReplId = 0x69113BF6u,
    kFortsUserorderbookReplInfoReplRev = 0x22660B54u,
    kFortsUserorderbookReplInfoReplAct = 0x50703499u,
    kFortsUserorderbookReplInfoMoment = 0xDE72BE0Eu,
    kFortsUserorderbookReplInfoPublicationState = 0xEFC8C1A6u,
    kFortsUserorderbookReplInfoTradesRev = 0xA10C70E3u,
    kFortsUserorderbookReplInfoTradesLifenum = 0x2837E570u,
    kFortsUserorderbookReplOrdersCurrentdayReplId = 0xF5D5E877u,
    kFortsUserorderbookReplOrdersCurrentdayReplRev = 0x5286AE83u,
    kFortsUserorderbookReplOrdersCurrentdayReplAct = 0x679C1696u,
    kFortsUserorderbookReplOrdersCurrentdayPublicOrderId = 0xCC0B3787u,
    kFortsUserorderbookReplOrdersCurrentdaySessId = 0x8EDBDD6Fu,
    kFortsUserorderbookReplOrdersCurrentdayClientCode = 0x7D3301BCu,
    kFortsUserorderbookReplOrdersCurrentdayMoment = 0x0B5BB2BFu,
    kFortsUserorderbookReplOrdersCurrentdayMomentNs = 0x2AA1EBBBu,
    kFortsUserorderbookReplOrdersCurrentdayXstatus = 0xD3D31F0Fu,
    kFortsUserorderbookReplOrdersCurrentdayXstatus2 = 0xB25A2D07u,
    kFortsUserorderbookReplOrdersCurrentdayPublicAction = 0x02C38B45u,
    kFortsUserorderbookReplOrdersCurrentdayIsinId = 0x774DCF48u,
    kFortsUserorderbookReplOrdersCurrentdayDir = 0xD4CB365Eu,
    kFortsUserorderbookReplOrdersCurrentdayPrice = 0x24FBC718u,
    kFortsUserorderbookReplOrdersCurrentdayPublicAmount = 0x74871F6Bu,
    kFortsUserorderbookReplOrdersCurrentdayPublicAmountRest = 0x46542CFAu,
    kFortsUserorderbookReplOrdersCurrentdayComment = 0x3F08CA28u,
    kFortsUserorderbookReplOrdersCurrentdayExtId = 0x3C0CD86Au,
    kFortsUserorderbookReplOrdersCurrentdayLoginFrom = 0xBC381729u,
    kFortsUserorderbookReplOrdersCurrentdayIdOrd1 = 0xDB219EBDu,
    kFortsUserorderbookReplOrdersCurrentdayPrivateOrderId = 0x10F9D1A7u,
    kFortsUserorderbookReplOrdersCurrentdayPrivateAmount = 0xE796BDCBu,
    kFortsUserorderbookReplOrdersCurrentdayPrivateAmountRest = 0x321E251Au,
    kFortsUserorderbookReplOrdersCurrentdayPrivateAction = 0x4C0E81A5u,
    kFortsUserorderbookReplMultilegOrdersCurrentdayReplId = 0x9717D593u,
    kFortsUserorderbookReplMultilegOrdersCurrentdayReplRev = 0xAEC401CFu,
    kFortsUserorderbookReplMultilegOrdersCurrentdayReplAct = 0x3717062Au,
    kFortsUserorderbookReplMultilegOrdersCurrentdayPublicOrderId = 0x1C84C503u,
    kFortsUserorderbookReplMultilegOrdersCurrentdaySessId = 0x69B1D503u,
    kFortsUserorderbookReplMultilegOrdersCurrentdayClientCode = 0xDCFD3708u,
    kFortsUserorderbookReplMultilegOrdersCurrentdayMoment = 0xC874C813u,
    kFortsUserorderbookReplMultilegOrdersCurrentdayMomentNs = 0xF1E94BF7u,
    kFortsUserorderbookReplMultilegOrdersCurrentdayXstatus = 0x15DD1ED3u,
    kFortsUserorderbookReplMultilegOrdersCurrentdayXstatus2 = 0x4C179C33u,
    kFortsUserorderbookReplMultilegOrdersCurrentdayPublicAction = 0x3E5694E1u,
    kFortsUserorderbookReplMultilegOrdersCurrentdayIsinId = 0x4C063E2Cu,
    kFortsUserorderbookReplMultilegOrdersCurrentdayDir = 0xF79FAA32u,
    kFortsUserorderbookReplMultilegOrdersCurrentdayPrice = 0xD99543BCu,
    kFortsUserorderbookReplMultilegOrdersCurrentdayPublicAmount = 0xBDB97B97u,
    kFortsUserorderbookReplMultilegOrdersCurrentdayPublicAmountRest = 0x696B7446u,
    kFortsUserorderbookReplMultilegOrdersCurrentdayComment = 0x8261C6F4u,
    kFortsUserorderbookReplMultilegOrdersCurrentdayExtId = 0xB667BECEu,
    kFortsUserorderbookReplMultilegOrdersCurrentdayLoginFrom = 0x5F743B7Du,
    kFortsUserorderbookReplMultilegOrdersCurrentdayIdOrd1 = 0xF58407E9u,
    kFortsUserorderbookReplMultilegOrdersCurrentdayPrivateOrderId = 0x5FBB5783u,
    kFortsUserorderbookReplMultilegOrdersCurrentdayPrivateAmount = 0x25902A17u,
    kFortsUserorderbookReplMultilegOrdersCurrentdayPrivateAmountRest = 0xE1D7DFC6u,
    kFortsUserorderbookReplMultilegOrdersCurrentdayPrivateAction = 0xA62D4361u,
    kFortsUserorderbookReplInfoCurrentdayReplId = 0xC0CC37D6u,
    kFortsUserorderbookReplInfoCurrentdayReplRev = 0x5E5EC274u,
    kFortsUserorderbookReplInfoCurrentdayReplAct = 0x8C68EBB9u,
    kFortsUserorderbookReplInfoCurrentdayPublicationState = 0x50256C46u,
    kFortsUserorderbookReplInfoCurrentdayTradesRev = 0xC717CD03u,
    kFortsUserorderbookReplInfoCurrentdayTradesLifenum = 0x20C14690u,
    kFortsUserorderbookReplInfoCurrentdayServerTime = 0x40CBD6CFu,
    kFortsAggrReplOrdersAggrReplId = 0x5A5F45FCu,
    kFortsAggrReplOrdersAggrReplRev = 0xAD27303Eu,
    kFortsAggrReplOrdersAggrReplAct = 0x24DEB93Fu,
    kFortsAggrReplOrdersAggrIsinId = 0xE7AF54D9u,
    kFortsAggrReplOrdersAggrPrice = 0x227D5731u,
    kFortsAggrReplOrdersAggrVolume = 0x5EEC2EF6u,
    kFortsAggrReplOrdersAggrMoment = 0xF71FC830u,
    kFortsAggrReplOrdersAggrMomentNs = 0x0A6627AEu,
    kFortsAggrReplOrdersAggrDir = 0x477A12BBu,
    kFortsAggrReplOrdersAggrSynthVolume = 0xF8617E71u,
    kFortsAggrReplSysEventsReplId = 0x5707D2E6u,
    kFortsAggrReplSysEventsReplRev = 0x69CC7A64u,
    kFortsAggrReplSysEventsReplAct = 0xFCDD3749u,
    kFortsAggrReplSysEventsEventType = 0x6C1A57C3u,
    kFortsAggrReplSysEventsEventId = 0xBA362516u,
    kFortsAggrReplSysEventsSessId = 0xC958CA70u,
    kFortsAggrReplSysEventsMessage = 0xEA55C171u,
    kFortsAggrReplSysEventsServerTime = 0x49CB067Fu,
    kFortsPosReplPositionReplId = 0x0C4C7D19u,
    kFortsPosReplPositionReplRev = 0xF3B25439u,
    kFortsPosReplPositionReplAct = 0x5084FC10u,
    kFortsPosReplPositionClientCode = 0x4681BCDAu,
    kFortsPosReplPositionIsinId = 0x4B216CBEu,
    kFortsPosReplPositionXpos = 0x7EA1CCD7u,
    kFortsPosReplPositionXbuysQty = 0x17D59F51u,
    kFortsPosReplPositionXsellsQty = 0x5FC83D43u,
    kFortsPosReplPositionXdayOpenQty = 0x3784F8CFu,
    kFortsPosReplPositionXdayOpenBuysQty = 0x4BE12CC7u,
    kFortsPosReplPositionXdayOpenSellsQty = 0xC36F20CDu,
    kFortsPosReplPositionXopenQty = 0xB895D710u,
    kFortsPosReplPositionWaprice = 0x757E04AAu,
    kFortsPosReplPositionNetVolumeRur = 0x0F687431u,
    kFortsPosReplPositionLastDealId = 0x3FBDDB48u,
    kFortsPosReplPositionLastQuantity = 0xB68CAA6Bu,
    kFortsPosReplPositionAccountType = 0x190D7061u,
    kFortsPosReplPositionSaReplId = 0x2E8440A8u,
    kFortsPosReplPositionSaReplRev = 0xF939DABAu,
    kFortsPosReplPositionSaReplAct = 0x7104EB73u,
    kFortsPosReplPositionSaClientCode = 0x86D8167Du,
    kFortsPosReplPositionSaIsinId = 0xA66B2CADu,
    kFortsPosReplPositionSaXpos = 0x07F307FAu,
    kFortsPosReplInfoReplId = 0x55F97258u,
    kFortsPosReplInfoReplRev = 0x0250DECAu,
    kFortsPosReplInfoReplAct = 0xDCA68723u,
    kFortsPosReplInfoTradesRev = 0x4A6A9B0Du,
    kFortsPosReplInfoTradesLifenum = 0x644B493Au,
    kFortsPosReplInfoServerTime = 0xE919C585u,
    kFortsPartReplPartReplId = 0xCDEC67C6u,
    kFortsPartReplPartReplRev = 0xB3056B04u,
    kFortsPartReplPartReplAct = 0x461494E9u,
    kFortsPartReplPartClientCode = 0x2DD249CFu,
    kFortsPartReplPartMoneyFree = 0x1BC22985u,
    kFortsPartReplPartMoneyBlocked = 0x4223AC59u,
    kFortsPartReplPartVmReserve = 0x57FD13ACu,
    kFortsPartReplPartFee = 0x76D481E2u,
    kFortsPartReplPartLimitsSet = 0x15046811u,
    kFortsPartReplPartMoneyOld = 0x3D146A68u,
    kFortsPartReplPartMoneyAmount = 0x519A3303u,
    kFortsPartReplPartMoneyPledgeAmount = 0x5989D90Fu,
    kFortsPartReplPartActualAmountOfBaseCurrency = 0x9FFF5FE5u,
    kFortsPartReplPartVmIntercl = 0xB002DE69u,
    kFortsPartReplPartIsAutoUpdateLimit = 0x4B0C8CC0u,
    kFortsPartReplPartBrokerFee = 0x2DD6A1A0u,
    kFortsPartReplPartPenalty = 0x2E26B627u,
    kFortsPartReplPartPremiumIntercl = 0xFD428D59u,
    kFortsPartReplPartNetOptionValue = 0xD48433A5u,
    kFortsPartReplPartSaReplId = 0xA45E6C5Du,
    kFortsPartReplPartSaReplRev = 0xBF60930Du,
    kFortsPartReplPartSaReplAct = 0x6ED1410Cu,
    kFortsPartReplPartSaMoneyAmount = 0x14C0EFB8u,
    kFortsPartReplPartSaMoneyFree = 0x4C3CF2CAu,
    kFortsPartReplSysEventsReplId = 0x7E71F1ACu,
    kFortsPartReplSysEventsReplRev = 0x636276CEu,
    kFortsPartReplSysEventsReplAct = 0x3E43FB2Fu,
    kFortsPartReplSysEventsEventType = 0x4D394161u,
    kFortsPartReplSysEventsEventId = 0xC6E1CA0Cu,
    kFortsPartReplSysEventsSessId = 0x51AA274Eu,
    kFortsPartReplSysEventsMessage = 0x4F56B473u,
    kFortsPartReplSysEventsServerTime = 0xD4A0B251u,
    kFortsRefdataReplFutSessContentsReplId = 0x9737CA14u,
    kFortsRefdataReplFutSessContentsReplRev = 0x1DA88716u,
    kFortsRefdataReplFutSessContentsReplAct = 0x17EADA17u,
    kFortsRefdataReplFutSessContentsSessId = 0xD7C818C6u,
    kFortsRefdataReplFutSessContentsIsinId = 0x929CA2D1u,
    kFortsRefdataReplFutSessContentsShortIsin = 0x2F56B664u,
    kFortsRefdataReplFutSessContentsIsin = 0x3B3C916Bu,
    kFortsRefdataReplFutSessContentsName = 0x6AD0D2B7u,
    kFortsRefdataReplFutSessContentsInstTerm = 0x13837AD3u,
    kFortsRefdataReplFutSessContentsBaseContractCode = 0x20B0445Cu,
    kFortsRefdataReplFutSessContentsLimitUp = 0xD1A9DE0Du,
    kFortsRefdataReplFutSessContentsLimitDown = 0xA9FABC2Cu,
    kFortsRefdataReplFutSessContentsSettlementPriceOpen = 0x8453894Eu,
    kFortsRefdataReplFutSessContentsRoundto = 0x8AE22F95u,
    kFortsRefdataReplFutSessContentsMinStep = 0xB4D33B47u,
    kFortsRefdataReplFutSessContentsLotVolume = 0xAF4230AEu,
    kFortsRefdataReplFutSessContentsStepPrice = 0xEF807F2Cu,
    kFortsRefdataReplFutSessContentsLastTradeDate = 0x0956CD32u,
    kFortsRefdataReplFutSessContentsIsSpread = 0x5BD0E1CAu,
    kFortsRefdataReplFutSessContentsSettlementPrice = 0xAF69B3E5u,
    kFortsRefdataReplFutSessContentsSigns = 0x7C2AAB2Au,
    kFortsRefdataReplFutSessContentsState = 0xFDE80621u,
    kFortsRefdataReplFutSessContentsStepPriceCurr = 0xBF391551u,
    kFortsRefdataReplFutSessContentsTradeModeId = 0xEAFC32D0u,
    kFortsRefdataReplFutSessContentsGroupMask = 0x72CB4528u,
    kFortsRefdataReplFutSessContentsTradePeriodAccess = 0xFFB9E6C9u,
    kFortsRefdataReplFutVcbReplId = 0xAA41B90Au,
    kFortsRefdataReplFutVcbReplRev = 0x7BFEA5B8u,
    kFortsRefdataReplFutVcbReplAct = 0x0F22EA55u,
    kFortsRefdataReplFutVcbBaseContractCode = 0x451C301Au,
    kFortsRefdataReplFutVcbCurr = 0x286FE7E2u,
    kFortsRefdataReplFutVcbBaseContractId = 0x1837336Eu,
    kFortsRefdataReplFutVcbBoardMd = 0xF39DEE9Au,
    kFortsRefdataReplFutInstrumentsReplId = 0x40D03DC1u,
    kFortsRefdataReplFutInstrumentsReplRev = 0x6FE268E1u,
    kFortsRefdataReplFutInstrumentsReplAct = 0x31BA1158u,
    kFortsRefdataReplFutInstrumentsIsinId = 0xAADB28A6u,
    kFortsRefdataReplFutInstrumentsShortIsin = 0x440A21D5u,
    kFortsRefdataReplFutInstrumentsIsin = 0xA8CECB56u,
    kFortsRefdataReplFutInstrumentsName = 0xF483085Eu,
    kFortsRefdataReplFutInstrumentsInstTerm = 0x6AD0FA80u,
    kFortsRefdataReplFutInstrumentsBaseContractCode = 0x6C00CF29u,
    kFortsRefdataReplFutInstrumentsRoundto = 0x7C7354EEu,
    kFortsRefdataReplFutInstrumentsMinStep = 0x613E0F12u,
    kFortsRefdataReplFutInstrumentsLotVolume = 0x9A5295F7u,
    kFortsRefdataReplFutInstrumentsStepPrice = 0x7E39B195u,
    kFortsRefdataReplFutInstrumentsLastTradeDate = 0xF2537869u,
    kFortsRefdataReplFutInstrumentsIsSpread = 0x078AA2CDu,
    kFortsRefdataReplFutInstrumentsSettlementPrice = 0xB17F7830u,
    kFortsRefdataReplFutInstrumentsSigns = 0x5098D19Du,
    kFortsRefdataReplFutInstrumentsStepPriceCurr = 0xD3C47C3Au,
    kFortsRefdataReplFutInstrumentsTradeModeId = 0x943FB7B7u,
    kFortsRefdataReplFutInstrumentsGroupMask = 0x41CA41DDu,
    kFortsRefdataReplFutInstrumentsTradePeriodAccess = 0x30EDE806u,
    kFortsRefdataReplSysMessagesReplId = 0x2E120247u,
    kFortsRefdataReplSysMessagesReplRev = 0xA55A88F3u,
    kFortsRefdataReplSysMessagesReplAct = 0x1D99EC66u,
    kFortsRefdataReplSysMessagesMsgId = 0xE2556080u,
    kFortsRefdataReplSysMessagesLangCode = 0xFC929F25u,
    kFortsRefdataReplSysMessagesTypeId = 0xA24C5B05u,
    kFortsRefdataReplSysMessagesMoment = 0xE5FF00EFu,
    kFortsRefdataReplSysMessagesText = 0xBF590818u,
    kFortsRefdataReplSysMessagesUrgency = 0x3F881E5Au,
    kFortsRefdataReplSysMessagesStatus = 0x36D7FC79u,
    kFortsRefdataReplSysMessagesMessageBody = 0x4D9DC68Bu,
    kFortsRefdataReplOptSessContentsReplId = 0x134A8BC6u,
    kFortsRefdataReplOptSessContentsReplRev = 0xE6381704u,
    kFortsRefdataReplOptSessContentsReplAct = 0x794740E9u,
    kFortsRefdataReplOptSessContentsSessId = 0xC0CB8610u,
    kFortsRefdataReplOptSessContentsIsinId = 0x44376D17u,
    kFortsRefdataReplOptSessContentsIsin = 0x69965F61u,
    kFortsRefdataReplOptSessContentsShortIsin = 0x0C81C2FAu,
    kFortsRefdataReplOptSessContentsName = 0x9FBD86D1u,
    kFortsRefdataReplOptSessContentsBaseContractCode = 0x8B5DD64Eu,
    kFortsRefdataReplOptSessContentsFutIsinId = 0x3329AF3Bu,
    kFortsRefdataReplOptSessContentsPut = 0xBEB9FD4Fu,
    kFortsRefdataReplOptSessContentsStrike = 0x6C9F70B0u,
    kFortsRefdataReplOptSessContentsRoundto = 0x62F05ADFu,
    kFortsRefdataReplOptSessContentsLastTradeDate = 0xAA4D4F3Cu,
    kFortsRefdataReplOptSessContentsSigns = 0xB12E600Cu,
    kFortsRefdataReplOptSessContentsSettlementPrice = 0x18EC37E7u,
    kFortsRefdataReplOptSessContentsOptionSeriesId = 0xE466189Bu,
    kFortsRefdataReplOptSessContentsState = 0x93537E3Fu,
    kFortsRefdataReplOptSessContentsTradeModeId = 0x36BAC17Au,
    kFortsRefdataReplOptSessContentsGroupMask = 0x722DB996u,
    kFortsRefdataReplOptSessContentsTradePeriodAccess = 0x6213252Fu,
    kFortsRefdataReplMultilegDictReplId = 0xAF8ECC9Bu,
    kFortsRefdataReplMultilegDictReplRev = 0x69C348D7u,
    kFortsRefdataReplMultilegDictReplAct = 0xD3F2B312u,
    kFortsRefdataReplMultilegDictSessId = 0x9298B45Bu,
    kFortsRefdataReplMultilegDictIsinId = 0xF84407F4u,
    kFortsRefdataReplMultilegDictIsinIdLeg = 0xE7784753u,
    kFortsRefdataReplMultilegDictQtyRatio = 0x00DBE9B5u,
    kFortsRefdataReplMultilegDictLegOrderNo = 0x09F2C0B0u,
    kFortsRefdataReplInstr2matchingMapReplId = 0xD96FB493u,
    kFortsRefdataReplInstr2matchingMapReplRev = 0x1F180ECFu,
    kFortsRefdataReplInstr2matchingMapReplAct = 0xA76B132Au,
    kFortsRefdataReplInstr2matchingMapBaseContractId = 0x0E42ABFBu,
    kFortsRefdataReplInstr2matchingMapMatchingId = 0x0ED1FC24u,
    kFortsRefdataReplSessionReplId = 0x83365F57u,
    kFortsRefdataReplSessionReplRev = 0x033D3B23u,
    kFortsRefdataReplSessionReplAct = 0x1852A336u,
    kFortsRefdataReplSessionSessId = 0x9FF9B38Fu,
    kFortsRefdataReplSessionBegin = 0xA78B39E0u,
    kFortsRefdataReplSessionEnd = 0xE936392Cu,
    kFortsRefdataReplSessionState = 0xDCAECBD0u,
    kFortsRefdataReplSessionEveOn = 0xD2363021u,
    kFortsRefdataReplSessionEveBegin = 0xBBF577ADu,
    kFortsRefdataReplSessionEveEnd = 0xD1ABE1FDu,
    kFortsRefdataReplSessionMonOn = 0x55A2C699u,
    kFortsRefdataReplSessionMonBegin = 0x2E664475u,
    kFortsRefdataReplSessionMonEnd = 0x806F2575u,
    kFortsRefdataReplSessionSettlSessBegin = 0x49D86842u,
    kFortsRefdataReplSessionClrSessBegin = 0x7D5CDB93u,
    kFortsRefdataReplSessionSettlPriceCalcTime = 0x30FDA647u,
    kFortsRefdataReplSessionSettlSessT1Begin = 0x38C2ACD8u,
    kFortsRefdataReplSessionMarginCallFixSchedule = 0x9546E532u,
    kFortsSessionstateReplSessionStateReplId = 0x7F1A92A5u,
    kFortsSessionstateReplSessionStateReplRev = 0xEFC43BF5u,
    kFortsSessionstateReplSessionStateReplAct = 0x5CAA84B4u,
    kFortsSessionstateReplSessionStateSessId = 0xB4D073BDu,
    kFortsSessionstateReplSessionStatePublicState = 0xB8D57CA2u,
    kFortsInstrumentstateReplInstrumentStateReplId = 0xFD093F21u,
    kFortsInstrumentstateReplInstrumentStateReplRev = 0x5F7AFD01u,
    kFortsInstrumentstateReplInstrumentStateReplAct = 0x1ED83C78u,
    kFortsInstrumentstateReplInstrumentStateIsinId = 0x7EAE31C6u,
    kFortsInstrumentstateReplInstrumentStatePublicState = 0x7C003BB6u,
};

struct TypeDescriptor {
    std::string_view type_token;
    ValueClass value_class;
    std::uint16_t decimal_digits;
    std::uint16_t decimal_scale;
};

struct StreamDescriptor {
    StreamCode stream_code;
    std::string_view stream_name;
    std::uint32_t first_table_index;
    std::uint32_t table_count;
};

struct TableDescriptor {
    TableCode table_code;
    std::uint32_t stream_id;
    std::string_view stream_name;
    std::string_view table_name;
    std::uint32_t first_field_index;
    std::uint32_t field_count;
};

struct FieldDescriptor {
    FieldCode field_code;
    std::string_view field_name;
    std::string_view type_token;
    ValueClass value_class;
    std::uint16_t storage_size_bytes;
    std::uint16_t decimal_digits;
    std::uint16_t decimal_scale;
    bool service_field;
};

inline constexpr std::size_t kTypeCount = 18;
inline constexpr std::size_t kStreamCount = 9;
inline constexpr std::size_t kTableCount = 35;
inline constexpr std::size_t kFieldCount = 278;

std::span<const TypeDescriptor> TypeDescriptors();
std::span<const StreamDescriptor> StreamDescriptors();
std::span<const TableDescriptor> TableDescriptors();
std::span<const FieldDescriptor> FieldDescriptors();

const TypeDescriptor* FindTypeByToken(std::string_view type_token);
const StreamDescriptor* FindStreamByCode(StreamCode stream_code);
const TableDescriptor* FindTableByCode(TableCode table_code);
const FieldDescriptor* FindFieldByCode(FieldCode field_code);
std::span<const TableDescriptor> TablesForStream(StreamCode stream_code);
std::span<const FieldDescriptor> FieldsForTable(TableCode table_code);

} // namespace moex::plaza2::generated
