#!/usr/bin/env python3
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "tools"))

from moex_phase0_common import load_json_yaml


REQUIRED_COMMAND_NAMES = {
    "AddOrder",
    "IcebergAddOrder",
    "DelOrder",
    "IcebergDelOrder",
    "MoveOrder",
    "IcebergMoveOrder",
    "DelUserOrders",
    "DelOrdersByBFLimit",
    "CODHeartbeat",
}


def require(condition: bool, message: str) -> None:
    if not condition:
        raise AssertionError(message)


def main() -> int:
    if len(sys.argv) not in {2, 3}:
        raise SystemExit("usage: assert_plaza2_trade_codec_materialize.py <repo-root> [materializer]")

    root = Path(sys.argv[1]).resolve()
    materializer = Path(sys.argv[2]).resolve() if len(sys.argv) == 3 else root / "tools/plaza2_phase5b_trade_codec_materialize.py"
    command = [str(materializer), "--project-root", str(root), "--check"]
    if materializer.suffix == ".py":
        command.insert(0, sys.executable)
    result = subprocess.run(command, check=False, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    require(result.returncode == 0, result.stderr)

    metadata = load_json_yaml(root / "connectors/plaza2_trade/generated/plaza2_trade_generated_metadata.json")
    require(metadata["version"] == 1, "generated metadata version mismatch")
    require("Generated by tools/plaza2_phase5b_trade_codec_materialize.py" in metadata["generated_by"],
            "generated marker missing")

    command_names = {item["command_name"] for item in metadata["commands"]}
    require(command_names == REQUIRED_COMMAND_NAMES, "generated command coverage mismatch")
    for command_item in metadata["commands"]:
        require(command_item["offline_only"] is True, "generated command should be offline-only")
        require(command_item["sendable"] is False, "generated command must not be sendable")
        require(command_item["fields"], "generated command missing fields")
        require(command_item["encoded_payload_size"] == sum(field["encoded_size"] for field in command_item["fields"]),
                "encoded payload size mismatch")

    print("Phase 5B PLAZA II trade codec materialize assertions passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
