#!/usr/bin/env python3
from __future__ import annotations

import argparse
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from moex_phase0_common import dump_json, load_json_yaml


GENERATED_NOTICE = "Generated by tools/plaza2_phase5b_trade_codec_materialize.py; do not edit by hand."


def type_size(type_token: str) -> int:
    if type_token.startswith("c"):
        return int(type_token[1:])
    if type_token == "i1":
        return 1
    if type_token == "i4":
        return 4
    if type_token == "i8":
        return 8
    raise ValueError(f"unsupported Phase 5B field type token: {type_token}")


def load_items(root: Path, relative: str) -> list[dict]:
    payload = load_json_yaml(root / relative)
    if payload.get("version") != 1:
        raise ValueError(f"{relative} version mismatch")
    return list(payload["items"])


def materialized_payload(project_root: Path) -> dict:
    commands = load_items(project_root, "matrix/protocol_inventory/plaza2_trade_commands.yaml")
    fields = load_items(project_root, "matrix/protocol_inventory/plaza2_trade_command_fields.yaml")
    replies = load_items(project_root, "matrix/protocol_inventory/plaza2_trade_replies.yaml")
    errors = load_items(project_root, "matrix/protocol_inventory/plaza2_trade_errors.yaml")

    fields_by_command: dict[str, list[dict]] = {}
    for field in sorted(fields, key=lambda item: (item["command_name"], item["ordinal"], item["field_name"])):
        item = dict(field)
        item["encoded_size"] = type_size(str(item["type_token"]))
        fields_by_command.setdefault(str(item["command_id"]), []).append(item)

    command_items = []
    for command in sorted(commands, key=lambda item: item["msgid"]):
        item = dict(command)
        item["fields"] = fields_by_command.get(item["protocol_item_id"], [])
        item["encoded_payload_size"] = sum(field["encoded_size"] for field in item["fields"])
        item["offline_only"] = True
        item["sendable"] = False
        command_items.append(item)

    return {
        "__generated_marker": "Generated file, do not edit.",
        "generated_by": GENERATED_NOTICE,
        "version": 1,
        "source_matrices": [
            "matrix/protocol_inventory/plaza2_trade_commands.yaml",
            "matrix/protocol_inventory/plaza2_trade_command_fields.yaml",
            "matrix/protocol_inventory/plaza2_trade_replies.yaml",
            "matrix/protocol_inventory/plaza2_trade_errors.yaml",
        ],
        "commands": command_items,
        "replies": sorted(replies, key=lambda item: item["msgid"]),
        "errors": sorted(errors, key=lambda item: item["msgid"]),
    }


def materialize(project_root: Path, check: bool) -> int:
    target = project_root / "connectors/plaza2_trade/generated/plaza2_trade_generated_metadata.json"
    payload = materialized_payload(project_root)
    if check:
        with tempfile.TemporaryDirectory(prefix="plaza2-phase5b-") as tmp_raw:
            tmp = Path(tmp_raw) / target.name
            dump_json(payload, tmp)
            expected = tmp.read_text(encoding="utf-8")
        actual = target.read_text(encoding="utf-8") if target.exists() else ""
        if actual != expected:
            print("Phase 5B trade codec generated metadata is stale", file=sys.stderr)
            return 1
        print("Phase 5B PLAZA II trade codec materialize check passed")
        return 0
    dump_json(payload, target)
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Materialize deterministic Phase 5B PLAZA II trade codec metadata.")
    parser.add_argument("--project-root", default=".")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    return materialize(Path(args.project_root).resolve(), args.check)


if __name__ == "__main__":
    raise SystemExit(main())
