#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
import tempfile

from moex_phase0_common import dump_json
from plaza2_schema_common import cpp_pascal_case, cpp_string_literal, parse_reviewed_scheme


SCOPE_BUCKET_ENUM = {
    "private_core": "kPrivateCore",
    "private_auxiliary": "kPrivateAuxiliary",
    "public_common": "kPublicCommon",
    "public_aggr": "kPublicAggr",
    "public_ordlog": "kPublicOrdlog",
    "deferred": "kDeferred",
}

VALUE_CLASS_ENUM = {
    "signed_integer": "kSignedInteger",
    "unsigned_integer": "kUnsignedInteger",
    "fixed_string": "kFixedString",
    "decimal": "kDecimal",
    "floating_point": "kFloatingPoint",
    "timestamp": "kTimestamp",
    "binary": "kBinary",
}

WIRE_TYPE_ENUM = {
    "a": "kA",
    "bN": "kBinaryPayload",
    "cN": "kCString",
    "d": "kDecimal",
    "f": "kFloat64",
    "i1": "kI1",
    "i2": "kI2",
    "i4": "kI4",
    "i8": "kI8",
    "t": "kTimestamp",
    "u1": "kU1",
    "u2": "kU2",
    "u4": "kU4",
    "u8": "kU8",
    "zN": "kSizedBinaryPayload",
}

STREAM_TYPE_ENUM = {
    "I": "kSnapshot",
    "R": "kReplication",
    "AR": "kAuxiliaryReplication",
}

LOGIN_SUBTYPE_BITS = {
    "main": 0x01,
    "viewing": 0x02,
    "transactional": 0x04,
}


def render_json(parsed: dict) -> str:
    compact_fields = [
        {
            "stream_name": row["stream_name"],
            "table_name": row["table_name"],
            "field_name": row["field_name"],
            "field_id": row["field_id"],
            "stream_id": row["stream_id"],
            "table_id": row["table_id"],
            "type_id": row["type_id"],
            "type_token": row["type_token"],
            "value_class": row["value_class"],
            "cpp_type": row["cpp_type"],
            "cpp_type_comment": row["cpp_type_comment"],
            "storage_size_bytes": row["storage_size_bytes"],
            "logical_length": row["logical_length"],
            "decimal_digits": row["decimal_digits"],
            "decimal_scale": row["decimal_scale"],
            "service_field": row["service_field"],
        }
        for row in parsed["fields"]
    ]
    payload = {
        "generated_by": "Generated by tools/plaza2_codegen.py; generated file, do not edit.",
        "version": 1,
        "schema": parsed["schema"],
        "types": parsed["types"],
        "streams": parsed["streams"],
        "tables": parsed["tables"],
        "fields": compact_fields,
    }
    return json.dumps(payload, indent=2, sort_keys=False) + "\n"


def render_enum(enum_name: str, rows: list[tuple[str, int]]) -> list[str]:
    lines = [f"enum class {enum_name} : std::uint32_t {{"]
    for name, numeric_id in rows:
        lines.append(f"    {name} = 0x{numeric_id:08X}u,")
    lines.append("};")
    return lines


def render_header(parsed: dict) -> str:
    schema = parsed["schema"]
    stream_enum_rows = [(f"k{cpp_pascal_case(row['stream_name'])}", row["stream_id"]) for row in parsed["streams"]]
    table_enum_rows = [
        (f"k{cpp_pascal_case(row['stream_name'])}{cpp_pascal_case(row['table_name'])}", row["table_id"])
        for row in parsed["tables"]
    ]
    field_enum_rows = [
        (
            f"k{cpp_pascal_case(row['stream_name'])}{cpp_pascal_case(row['table_name'])}{cpp_pascal_case(row['field_name'])}",
            row["field_id"],
        )
        for row in parsed["fields"]
    ]

    lines = [
        "#pragma once",
        "",
        "// Generated by tools/plaza2_codegen.py from the reviewed Phase 3B PLAZA II scheme fixture.",
        "// Source artifact: " + schema["source_relative_path"],
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "#include <span>",
        "#include <string_view>",
        "",
        "namespace moex::plaza2::generated {",
        "",
        "enum class ScopeBucket : std::uint8_t {",
        "    kPrivateCore = 0,",
        "    kPrivateAuxiliary = 1,",
        "    kPublicCommon = 2,",
        "    kPublicAggr = 3,",
        "    kPublicOrdlog = 4,",
        "    kDeferred = 5,",
        "};",
        "",
        "enum class StreamType : std::uint8_t {",
        "    kSnapshot = 0,",
        "    kReplication = 1,",
        "    kAuxiliaryReplication = 2,",
        "};",
        "",
        "enum class ValueClass : std::uint8_t {",
        "    kSignedInteger = 0,",
        "    kUnsignedInteger = 1,",
        "    kFixedString = 2,",
        "    kDecimal = 3,",
        "    kFloatingPoint = 4,",
        "    kTimestamp = 5,",
        "    kBinary = 6,",
        "};",
        "",
        "enum class WireType : std::uint8_t {",
        "    kA = 0,",
        "    kBinaryPayload = 1,",
        "    kCString = 2,",
        "    kDecimal = 3,",
        "    kFloat64 = 4,",
        "    kI1 = 5,",
        "    kI2 = 6,",
        "    kI4 = 7,",
        "    kI8 = 8,",
        "    kTimestamp = 9,",
        "    kU1 = 10,",
        "    kU2 = 11,",
        "    kU4 = 12,",
        "    kU8 = 13,",
        "    kSizedBinaryPayload = 14,",
        "};",
        "",
    ]
    lines.extend(render_enum("StreamCode", stream_enum_rows))
    lines.append("")
    lines.extend(render_enum("TableCode", table_enum_rows))
    lines.append("")
    lines.extend(render_enum("FieldCode", field_enum_rows))
    lines.extend(
        [
            "",
            "struct TypeDescriptor {",
            "    std::uint32_t type_id;",
            "    std::string_view type_token;",
            "    std::string_view cgate_type;",
            "    std::string_view sql_type;",
            "    std::string_view cpp_type;",
            "    std::string_view cpp_type_comment;",
            "    std::string_view description;",
            "    WireType wire_type;",
            "    ValueClass value_class;",
            "    std::uint16_t storage_size_bytes;",
            "    std::uint16_t logical_length;",
            "    std::uint16_t decimal_digits;",
            "    std::uint16_t decimal_scale;",
            "};",
            "",
            "struct StreamDescriptor {",
            "    StreamCode stream_code;",
            "    std::uint32_t stream_id;",
            "    std::string_view protocol_item_id;",
            "    std::string_view stream_name;",
            "    std::string_view stream_anchor_name;",
            "    std::string_view title;",
            "    std::string_view scheme_filename;",
            "    std::string_view scheme_section;",
            "    StreamType stream_type;",
            "    ScopeBucket scope_bucket;",
            "    std::uint8_t login_subtype_mask;",
            "    bool matching_partitioned;",
            "    std::uint32_t first_table_index;",
            "    std::uint32_t table_count;",
            "};",
            "",
            "struct TableDescriptor {",
            "    TableCode table_code;",
            "    std::uint32_t table_id;",
            "    std::uint32_t stream_id;",
            "    std::string_view protocol_item_id;",
            "    std::string_view stream_name;",
            "    std::string_view table_name;",
            "    std::string_view title;",
            "    ScopeBucket scope_bucket;",
            "    std::uint32_t first_field_index;",
            "    std::uint32_t field_count;",
            "};",
            "",
            "struct FieldDescriptor {",
            "    FieldCode field_code;",
            "    std::uint32_t field_id;",
            "    std::uint32_t stream_id;",
            "    std::uint32_t table_id;",
            "    std::uint32_t type_id;",
            "    std::string_view stream_name;",
            "    std::string_view table_name;",
            "    std::string_view field_name;",
            "    std::string_view type_token;",
            "    std::string_view cpp_type;",
            "    std::string_view cpp_type_comment;",
            "    ValueClass value_class;",
            "    WireType wire_type;",
            "    std::uint16_t storage_size_bytes;",
            "    std::uint16_t logical_length;",
            "    std::uint16_t decimal_digits;",
            "    std::uint16_t decimal_scale;",
            "    bool service_field;",
            "};",
            "",
            f"inline constexpr std::size_t kTypeCount = {len(parsed['types'])};",
            f"inline constexpr std::size_t kStreamCount = {len(parsed['streams'])};",
            f"inline constexpr std::size_t kTableCount = {len(parsed['tables'])};",
            f"inline constexpr std::size_t kFieldCount = {len(parsed['fields'])};",
            "",
            "std::span<const TypeDescriptor> TypeDescriptors();",
            "std::span<const StreamDescriptor> StreamDescriptors();",
            "std::span<const TableDescriptor> TableDescriptors();",
            "std::span<const FieldDescriptor> FieldDescriptors();",
            "",
            "const TypeDescriptor* FindTypeByToken(std::string_view type_token);",
            "const StreamDescriptor* FindStreamByCode(StreamCode stream_code);",
            "const TableDescriptor* FindTableByCode(TableCode table_code);",
            "const FieldDescriptor* FindFieldByCode(FieldCode field_code);",
            "std::span<const TableDescriptor> TablesForStream(StreamCode stream_code);",
            "std::span<const FieldDescriptor> FieldsForTable(TableCode table_code);",
            "",
            "constexpr bool IsInteger(ValueClass value_class) {",
            "    return value_class == ValueClass::kSignedInteger || value_class == ValueClass::kUnsignedInteger;",
            "}",
            "",
            "constexpr bool HasScale(ValueClass value_class) {",
            "    return value_class == ValueClass::kDecimal;",
            "}",
            "",
            "constexpr bool IsStringLike(ValueClass value_class) {",
            "    return value_class == ValueClass::kFixedString;",
            "}",
            "",
            "} // namespace moex::plaza2::generated",
            "",
        ]
    )
    return "\n".join(lines)


def login_mask(login_subtypes: list[str]) -> int:
    mask = 0
    for subtype in login_subtypes:
        bit = LOGIN_SUBTYPE_BITS.get(subtype)
        if bit is None:
            raise ValueError(f"unsupported login subtype {subtype}")
        mask |= bit
    return mask


def render_cpp(parsed: dict) -> str:
    type_by_id = {row["type_id"]: row for row in parsed["types"]}
    lines = [
        '// Generated by tools/plaza2_codegen.py from the reviewed Phase 3B PLAZA II scheme fixture.',
        '#include "plaza2_generated_metadata.hpp"',
        "",
        "#include <array>",
        "",
        "namespace moex::plaza2::generated {",
        "namespace {",
        "",
        "constexpr std::array<TypeDescriptor, kTypeCount> kTypeDescriptors{{",
    ]

    for row in parsed["types"]:
        lines.extend(
            [
                "    {",
                f"        0x{row['type_id']:08X}u,",
                f"        {cpp_string_literal(row['type_token'])},",
                f"        {cpp_string_literal(row['cgate_type'])},",
                f"        {cpp_string_literal(row['sql_type'])},",
                f"        {cpp_string_literal(row['cpp_type'])},",
                f"        {cpp_string_literal(row['cpp_type_comment'])},",
                f"        {cpp_string_literal(row['description'])},",
                f"        WireType::{WIRE_TYPE_ENUM[row['wire_type_name']]},",
                f"        ValueClass::{VALUE_CLASS_ENUM[row['value_class']]},",
                f"        {row['storage_size_bytes']},",
                f"        {row['logical_length']},",
                f"        {row['decimal_digits']},",
                f"        {row['decimal_scale']},",
                "    },",
            ]
        )
    lines.extend(["}};", "", "constexpr std::array<StreamDescriptor, kStreamCount> kStreamDescriptors{{"])

    for row in parsed["streams"]:
        lines.extend(
            [
                "    {",
                f"        StreamCode::k{cpp_pascal_case(row['stream_name'])},",
                f"        0x{row['stream_id']:08X}u,",
                f"        {cpp_string_literal(row['protocol_item_id'])},",
                f"        {cpp_string_literal(row['stream_name'])},",
                f"        {cpp_string_literal(row['stream_anchor_name'])},",
                f"        {cpp_string_literal(row['title'])},",
                f"        {cpp_string_literal(row['scheme_filename'])},",
                f"        {cpp_string_literal(row['scheme_section'])},",
                f"        StreamType::{STREAM_TYPE_ENUM[row['stream_type']]},",
                f"        ScopeBucket::{SCOPE_BUCKET_ENUM[row['scope_bucket']]},",
                f"        0x{login_mask(row['login_subtypes']):02X}u,",
                f"        {'true' if row['matching_partitioned'] else 'false'},",
                f"        {row['first_table_index']},",
                f"        {row['table_count']},",
                "    },",
            ]
        )
    lines.extend(["}};", "", "constexpr std::array<TableDescriptor, kTableCount> kTableDescriptors{{"])

    for row in parsed["tables"]:
        lines.extend(
            [
                "    {",
                f"        TableCode::k{cpp_pascal_case(row['stream_name'])}{cpp_pascal_case(row['table_name'])},",
                f"        0x{row['table_id']:08X}u,",
                f"        0x{row['stream_id']:08X}u,",
                f"        {cpp_string_literal(row['protocol_item_id'])},",
                f"        {cpp_string_literal(row['stream_name'])},",
                f"        {cpp_string_literal(row['table_name'])},",
                f"        {cpp_string_literal(row['title'])},",
                f"        ScopeBucket::{SCOPE_BUCKET_ENUM[row['scope_bucket']]},",
                f"        {row['first_field_index']},",
                f"        {row['field_count']},",
                "    },",
            ]
        )
    lines.extend(["}};", "", "constexpr std::array<FieldDescriptor, kFieldCount> kFieldDescriptors{{"])

    for row in parsed["fields"]:
        type_row = type_by_id[row["type_id"]]
        field_code_name = (
            f"FieldCode::k{cpp_pascal_case(row['stream_name'])}"
            f"{cpp_pascal_case(row['table_name'])}"
            f"{cpp_pascal_case(row['field_name'])}"
        )
        lines.extend(
            [
                "    {",
                f"        {field_code_name},",
                f"        0x{row['field_id']:08X}u,",
                f"        0x{row['stream_id']:08X}u,",
                f"        0x{row['table_id']:08X}u,",
                f"        0x{row['type_id']:08X}u,",
                f"        {cpp_string_literal(row['stream_name'])},",
                f"        {cpp_string_literal(row['table_name'])},",
                f"        {cpp_string_literal(row['field_name'])},",
                f"        {cpp_string_literal(row['type_token'])},",
                f"        {cpp_string_literal(row['cpp_type'])},",
                f"        {cpp_string_literal(row['cpp_type_comment'])},",
                f"        ValueClass::{VALUE_CLASS_ENUM[row['value_class']]},",
                f"        WireType::{WIRE_TYPE_ENUM[type_row['wire_type_name']]},",
                f"        {row['storage_size_bytes']},",
                f"        {row['logical_length']},",
                f"        {row['decimal_digits']},",
                f"        {row['decimal_scale']},",
                f"        {'true' if row['service_field'] else 'false'},",
                "    },",
            ]
        )
    lines.extend(
        [
            "}};",
            "",
            "} // namespace",
            "",
            "std::span<const TypeDescriptor> TypeDescriptors() {",
            "    return kTypeDescriptors;",
            "}",
            "",
            "std::span<const StreamDescriptor> StreamDescriptors() {",
            "    return kStreamDescriptors;",
            "}",
            "",
            "std::span<const TableDescriptor> TableDescriptors() {",
            "    return kTableDescriptors;",
            "}",
            "",
            "std::span<const FieldDescriptor> FieldDescriptors() {",
            "    return kFieldDescriptors;",
            "}",
            "",
            "const TypeDescriptor* FindTypeByToken(std::string_view type_token) {",
            "    for (const auto& descriptor : kTypeDescriptors) {",
            "        if (descriptor.type_token == type_token) {",
            "            return &descriptor;",
            "        }",
            "    }",
            "    return nullptr;",
            "}",
            "",
            "const StreamDescriptor* FindStreamByCode(StreamCode stream_code) {",
            "    for (const auto& descriptor : kStreamDescriptors) {",
            "        if (descriptor.stream_code == stream_code) {",
            "            return &descriptor;",
            "        }",
            "    }",
            "    return nullptr;",
            "}",
            "",
            "const TableDescriptor* FindTableByCode(TableCode table_code) {",
            "    for (const auto& descriptor : kTableDescriptors) {",
            "        if (descriptor.table_code == table_code) {",
            "            return &descriptor;",
            "        }",
            "    }",
            "    return nullptr;",
            "}",
            "",
            "const FieldDescriptor* FindFieldByCode(FieldCode field_code) {",
            "    for (const auto& descriptor : kFieldDescriptors) {",
            "        if (descriptor.field_code == field_code) {",
            "            return &descriptor;",
            "        }",
            "    }",
            "    return nullptr;",
            "}",
            "",
            "std::span<const TableDescriptor> TablesForStream(StreamCode stream_code) {",
            "    const auto* stream = FindStreamByCode(stream_code);",
            "    if (stream == nullptr) {",
            "        return {};",
            "    }",
            "    return std::span<const TableDescriptor>(",
            "        kTableDescriptors.data() + stream->first_table_index,",
            "        stream->table_count);",
            "}",
            "",
            "std::span<const FieldDescriptor> FieldsForTable(TableCode table_code) {",
            "    const auto* table = FindTableByCode(table_code);",
            "    if (table == nullptr) {",
            "        return {};",
            "    }",
            "    return std::span<const FieldDescriptor>(",
            "        kFieldDescriptors.data() + table->first_field_index,",
            "        table->field_count);",
            "}",
            "",
            "} // namespace moex::plaza2::generated",
            "",
        ]
    )
    return "\n".join(lines)


def write_if_different(path: Path, text: str, check: bool) -> None:
    existing = path.read_text(encoding="utf-8") if path.exists() else None
    if existing == text:
        return
    if check:
        raise SystemExit(f"generated file is stale: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate deterministic PLAZA II metadata from the reviewed Phase 3B scheme fixture.")
    parser.add_argument("--schema", required=True)
    parser.add_argument("--out", required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    schema_path = Path(args.schema).resolve()
    output_dir = Path(args.out).resolve()
    parsed = parse_reviewed_scheme(schema_path)

    json_text = render_json(parsed)
    header_text = render_header(parsed)
    cpp_text = render_cpp(parsed)

    if args.check:
        with tempfile.TemporaryDirectory(prefix="plaza2-phase3b-codegen-") as temp_dir:
            temp_root = Path(temp_dir)
            temp_json = temp_root / "plaza2_generated_metadata.json"
            temp_header = temp_root / "plaza2_generated_metadata.hpp"
            temp_cpp = temp_root / "plaza2_generated_metadata.cpp"
            dump_json(json.loads(json_text), temp_json)
            temp_header.write_text(header_text, encoding="utf-8")
            temp_cpp.write_text(cpp_text, encoding="utf-8")

        write_if_different(output_dir / "plaza2_generated_metadata.json", json_text, True)
        write_if_different(output_dir / "plaza2_generated_metadata.hpp", header_text, True)
        write_if_different(output_dir / "plaza2_generated_metadata.cpp", cpp_text, True)
        return 0

    write_if_different(output_dir / "plaza2_generated_metadata.json", json_text, False)
    write_if_different(output_dir / "plaza2_generated_metadata.hpp", header_text, False)
    write_if_different(output_dir / "plaza2_generated_metadata.cpp", cpp_text, False)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
