#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path

from plaza2_fake_scenario_common import (
    VALUE_KIND_ENUM,
    load_plaza2_fake_scenarios,
    load_plaza2_metadata_index,
)
from plaza2_schema_common import cpp_string_literal


SCENARIOS_DIR = "tests/plaza2_cgate/scenarios"
METADATA_PATH = "protocols/plaza2_cgate/generated/plaza2_generated_metadata.json"
OUTPUT_JSON = "protocols/plaza2_cgate/generated/plaza2_fake_scenarios.json"
OUTPUT_HPP = "protocols/plaza2_cgate/generated/plaza2_fake_scenarios.hpp"
OUTPUT_CPP = "protocols/plaza2_cgate/generated/plaza2_fake_scenarios.cpp"


def write_if_different(destination: Path, text: str, check: bool) -> None:
    existing = destination.read_text(encoding="utf-8") if destination.exists() else None
    if existing == text:
        return
    if check:
        raise SystemExit(f"generated file is stale: {destination}")
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(text, encoding="utf-8")


def flatten_scenarios(scenarios: list[dict]) -> dict:
    scenario_streams: list[dict] = []
    events: list[dict] = []
    rows: list[dict] = []
    fields: list[dict] = []
    invariants: list[dict] = []
    scenario_specs: list[dict] = []

    for scenario in scenarios:
        first_stream_index = len(scenario_streams)
        for stream in scenario["streams"]:
            scenario_streams.append(stream)

        first_event_index = len(events)
        for event in scenario["events"]:
            first_row_index = len(rows)
            for row in event["rows"]:
                first_field_index = len(fields)
                for field in row["fields"]:
                    fields.append(field)
                rows.append(
                    {
                        "stream_name": row["stream_name"],
                        "table_name": row["table_name"],
                        "stream_code_token": row["stream_code_token"],
                        "table_code_token": row["table_code_token"],
                        "first_field_index": first_field_index,
                        "field_count": len(row["fields"]),
                    }
                )
            events.append(
                {
                    "type": event["type"],
                    "kind_enum": event["kind_enum"],
                    "stream_name": event["stream_name"],
                    "table_name": event["table_name"],
                    "stream_code_token": event["stream_code_token"],
                    "table_code_token": event["table_code_token"],
                    "first_row_index": first_row_index,
                    "row_count": len(event["rows"]),
                    "numeric_value": event["numeric_value"],
                    "text_value": event["text_value"],
                }
            )

        first_invariant_index = len(invariants)
        for invariant in scenario["invariants"]:
            invariants.append(invariant)

        scenario_specs.append(
            {
                "scenario_id": scenario["scenario_id"],
                "description": scenario["description"],
                "metadata_version": scenario["metadata_version"],
                "deterministic_seed": scenario["deterministic_seed"],
                "first_stream_index": first_stream_index,
                "stream_count": len(scenario["streams"]),
                "first_event_index": first_event_index,
                "event_count": len(scenario["events"]),
                "first_invariant_index": first_invariant_index,
                "invariant_count": len(scenario["invariants"]),
            }
        )

    return {
        "scenario_specs": scenario_specs,
        "scenario_streams": scenario_streams,
        "events": events,
        "rows": rows,
        "fields": fields,
        "invariants": invariants,
    }


def render_json_payload(flattened: dict) -> str:
    payload = {
        "generated_by": "Generated by tools/plaza2_fake_scenario_materialize.py; generated file, do not edit.",
        "version": 1,
        "source_scenarios_path": SCENARIOS_DIR,
        "source_metadata_path": METADATA_PATH,
        "scenario_count": len(flattened["scenario_specs"]),
        "row_count": len(flattened["rows"]),
        "field_value_count": len(flattened["fields"]),
        "scenarios": [
            {
                "scenario_id": row["scenario_id"],
                "description": row["description"],
                "metadata_version": row["metadata_version"],
                "deterministic_seed": row["deterministic_seed"],
                "stream_count": row["stream_count"],
                "event_count": row["event_count"],
                "invariant_count": row["invariant_count"],
            }
            for row in flattened["scenario_specs"]
        ],
        "events": [
            {
                "type": row["type"],
                "stream_name": row["stream_name"],
                "table_name": row["table_name"],
                "row_count": row["row_count"],
                "numeric_value": row["numeric_value"],
                "text_value": row["text_value"],
            }
            for row in flattened["events"]
        ],
    }
    return json.dumps(payload, indent=2, sort_keys=False) + "\n"


def render_header(flattened: dict) -> str:
    lines = [
        "#pragma once",
        "",
        "// Generated by tools/plaza2_fake_scenario_materialize.py from tests/plaza2_cgate/scenarios.",
        "// Generated file, do not edit.",
        "",
        '#include "moex/plaza2/cgate/plaza2_fake_engine.hpp"',
        "",
        "#include <span>",
        "#include <string_view>",
        "",
        "namespace moex::plaza2::fake {",
        "",
        f"inline constexpr std::size_t kFakeScenarioCount = {len(flattened['scenario_specs'])};",
        f"inline constexpr std::size_t kFakeScenarioStreamCount = {len(flattened['scenario_streams'])};",
        f"inline constexpr std::size_t kFakeScenarioEventCount = {len(flattened['events'])};",
        f"inline constexpr std::size_t kFakeScenarioRowCount = {len(flattened['rows'])};",
        f"inline constexpr std::size_t kFakeScenarioFieldValueCount = {len(flattened['fields'])};",
        f"inline constexpr std::size_t kFakeScenarioInvariantCount = {len(flattened['invariants'])};",
        "",
        "std::span<const ScenarioSpec> FakeScenarioSpecs();",
        "std::span<const generated::StreamCode> FakeScenarioStreamCodes();",
        "std::span<const EventSpec> FakeScenarioEvents();",
        "std::span<const RowSpec> FakeScenarioRows();",
        "std::span<const FieldValueSpec> FakeScenarioFieldValues();",
        "std::span<const InvariantSpec> FakeScenarioInvariants();",
        "",
        "[[nodiscard]] ScenarioDataView ViewForScenario(const ScenarioSpec& scenario);",
        "[[nodiscard]] const ScenarioSpec* FindScenarioById(std::string_view scenario_id);",
        "",
        "} // namespace moex::plaza2::fake",
    ]
    return "\n".join(lines) + "\n"


def render_cpp(flattened: dict) -> str:
    lines = [
        '#include "plaza2_fake_scenarios.hpp"',
        "",
        "// Generated by tools/plaza2_fake_scenario_materialize.py from tests/plaza2_cgate/scenarios.",
        "// Generated file, do not edit.",
        "",
        "#include <array>",
        "#include <span>",
        "",
        "namespace moex::plaza2::fake {",
        "",
        "namespace {",
    ]

    lines.append(
        f"constexpr std::array<ScenarioSpec, {len(flattened['scenario_specs'])}> kScenarioSpecs{{{{"
    )
    for row in flattened["scenario_specs"]:
        lines.append(
            "    {"
            f"{cpp_string_literal(row['scenario_id'])}, "
            f"{cpp_string_literal(row['description'])}, "
            f"{row['metadata_version']}u, "
            f"{row['deterministic_seed']}u, "
            f"{row['first_stream_index']}u, "
            f"{row['stream_count']}u, "
            f"{row['first_event_index']}u, "
            f"{row['event_count']}u, "
            f"{row['first_invariant_index']}u, "
            f"{row['invariant_count']}u"
            "},"
        )
    lines.append("}};")
    lines.append("")

    lines.append(
        f"constexpr std::array<generated::StreamCode, {len(flattened['scenario_streams'])}> kScenarioStreams{{{{"
    )
    for row in flattened["scenario_streams"]:
        lines.append(f"    {row['stream_code_token']},")
    lines.append("}};")
    lines.append("")

    lines.append(f"constexpr std::array<EventSpec, {len(flattened['events'])}> kEventSpecs{{{{")
    for row in flattened["events"]:
        lines.append(
            "    {"
            f"{row['kind_enum']}, "
            f"{row['stream_code_token']}, "
            f"{row['table_code_token']}, "
            f"{row['first_row_index']}u, "
            f"{row['row_count']}u, "
            f"{row['numeric_value']}u, "
            f"{cpp_string_literal(row['text_value'])}"
            "},"
        )
    lines.append("}};")
    lines.append("")

    lines.append(f"constexpr std::array<RowSpec, {len(flattened['rows'])}> kRowSpecs{{{{")
    for row in flattened["rows"]:
        lines.append(
            "    {"
            f"{row['stream_code_token']}, "
            f"{row['table_code_token']}, "
            f"{row['first_field_index']}u, "
            f"{row['field_count']}u"
            "},"
        )
    lines.append("}};")
    lines.append("")

    lines.append(f"constexpr std::array<FieldValueSpec, {len(flattened['fields'])}> kFieldValueSpecs{{{{")
    for row in flattened["fields"]:
        lines.append(
            "    {"
            f"{row['field_code_token']}, "
            f"{VALUE_KIND_ENUM[row['value_kind']]}, "
            f"{row['signed_value']}, "
            f"{row['unsigned_value']}u, "
            f"{cpp_string_literal(row['text_value'])}"
            "},"
        )
    lines.append("}};")
    lines.append("")

    lines.append(
        f"constexpr std::array<InvariantSpec, {len(flattened['invariants'])}> kInvariantSpecs{{{{"
    )
    for row in flattened["invariants"]:
        bool_token = "true" if row["bool_value"] else "false"
        lines.append(
            "    {"
            f"{row['kind_enum']}, "
            f"{row['stream_code_token']}, "
            f"{row['numeric_value']}u, "
            f"{bool_token}, "
            f"{cpp_string_literal(row['text_value'])}"
            "},"
        )
    lines.append("}};")
    lines.extend(
        [
            "",
            "} // namespace",
            "",
            "std::span<const ScenarioSpec> FakeScenarioSpecs() { return kScenarioSpecs; }",
            "std::span<const generated::StreamCode> FakeScenarioStreamCodes() { return kScenarioStreams; }",
            "std::span<const EventSpec> FakeScenarioEvents() { return kEventSpecs; }",
            "std::span<const RowSpec> FakeScenarioRows() { return kRowSpecs; }",
            "std::span<const FieldValueSpec> FakeScenarioFieldValues() { return kFieldValueSpecs; }",
            "std::span<const InvariantSpec> FakeScenarioInvariants() { return kInvariantSpecs; }",
            "",
            "ScenarioDataView ViewForScenario(const ScenarioSpec& scenario) {",
            "    return {",
            "        .scenario = scenario,",
            "        .streams = std::span<const generated::StreamCode>(kScenarioStreams).subspan(",
            "            scenario.first_stream_index, scenario.stream_count),",
            "        .events = std::span<const EventSpec>(kEventSpecs).subspan(",
            "            scenario.first_event_index, scenario.event_count),",
            "        .rows = kRowSpecs,",
            "        .fields = kFieldValueSpecs,",
            "        .invariants = std::span<const InvariantSpec>(kInvariantSpecs).subspan(",
            "            scenario.first_invariant_index, scenario.invariant_count),",
            "    };",
            "}",
            "",
            "const ScenarioSpec* FindScenarioById(std::string_view scenario_id) {",
            "    for (const auto& scenario : kScenarioSpecs) {",
            "        if (scenario.scenario_id == scenario_id) {",
            "            return &scenario;",
            "        }",
            "    }",
            "    return nullptr;",
            "}",
            "",
            "} // namespace moex::plaza2::fake",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Validate and materialize Phase 3D PLAZA II fake-engine YAML scenarios."
    )
    parser.add_argument("--project-root", default=".")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    project_root = Path(args.project_root).resolve()
    metadata_index = load_plaza2_metadata_index(project_root / METADATA_PATH)
    scenarios = load_plaza2_fake_scenarios(project_root / SCENARIOS_DIR, metadata_index)
    flattened = flatten_scenarios(scenarios)

    json_text = render_json_payload(flattened)
    header_text = render_header(flattened)
    cpp_text = render_cpp(flattened)

    write_if_different(project_root / OUTPUT_JSON, json_text, args.check)
    write_if_different(project_root / OUTPUT_HPP, header_text, args.check)
    write_if_different(project_root / OUTPUT_CPP, cpp_text, args.check)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
