"""Generate native public records from the official schemetool/offsetof lock."""
from __future__ import annotations

import json
from pathlib import Path


def render_public_wire(lock_path: Path, parsed: dict) -> str:
    lock = json.loads(lock_path.read_text(encoding="utf-8"))
    lines = ["#pragma once", "", "// Generated by tools/plaza2_codegen.py; do not edit.",
             "// Official CGate 9.9 schemetool layouts: spec-lock/test/plaza2/public99/wire.json",
             '#include "plaza2_generated_metadata.hpp"', "#include <array>", "#include <cstddef>",
             "#include <cstdint>", "#include <span>", "#include <string_view>", "",
             "namespace moex::plaza2::public_wire {", "#pragma pack(push, 4)",
             "struct Time {", "    std::uint16_t year;", "    std::uint8_t month, day, hour, minute, second;",
             "    std::uint16_t msec;", "};", "static_assert(sizeof(Time) == 10 && offsetof(Time, msec) == 8);",
             "using Bcd16_5 = std::array<std::uint8_t, 11>;", ""]
    names = []
    table_ids = {(t["stream_name"], t["table_name"]): t["table_id"] for t in parsed["tables"]}
    for t in lock["tables"]:
        expected = [(f["field_name"], f["type_token"]) for f in parsed["fields"]
                    if f["stream_name"] == t["stream"] and f["table_name"] == t["table"]]
        actual = [(f["name"], f["type"]) for f in t["fields"]]
        if expected != actual:
            raise ValueError(f"official public wire differs from reviewed fields: {t['table']}")
        name = t["namespace"] + "".join(w.capitalize() for w in t["table"].split("_"))
        names.append(name)
        lines += [f"struct {name} {{"]
        for f in t["fields"]:
            token = f["type"]
            cpp = {"i1": "std::int8_t", "i4": "std::int32_t", "i8": "std::int64_t",
                   "u8": "std::uint64_t", "d16.5": "Bcd16_5", "t": "Time", "c64": "std::array<char, 65>"}[token]
            lines += [f"    {cpp} {f['name']};"]
        lines += ["};", f"static_assert(sizeof({name}) == {t['size']});"]
        for f in t["fields"]:
            lines += [f"static_assert(offsetof({name}, {f['name']}) == {f['offset']});"]
        lines += [""]
    lines += ["#pragma pack(pop)", "", "struct Field {", "    std::string_view name, type;",
              "    std::uint16_t offset, size;", "};", "struct Table {",
              "    generated::StreamCode stream;", "    generated::TableCode code;",
              "    std::string_view name;", "    std::uint16_t index, size;",
              "    std::span<const Field> fields;", "};", ""]
    for t, name in zip(lock["tables"], names):
        lines += [f"inline constexpr std::array<Field, {len(t['fields'])}> k{name}Fields = {{{{"]
        for f in t["fields"]:
            lines += [f'    {{"{f["name"]}", "{f["type"]}", {f["offset"]}, {f["size"]}}},']
        lines += ["}};"]
    lines += ["inline constexpr std::array<Table, 10> kTables = {{"]
    for t, name in zip(lock["tables"], names):
        stream = "kFortsOrdlogRepl" if t["namespace"] == "Ordlog" else "kFortsOrdbookRepl"
        code = table_ids[t["stream"], t["table"]]
        lines += [f"    {{generated::StreamCode::{stream}, static_cast<generated::TableCode>({code}U),",
                  f'     "{t["table"]}", {t["index"]}, {t["size"]}, k{name}Fields}},']
    lines += ["}};", "} // namespace moex::plaza2::public_wire", ""]
    return "\n".join(lines)
