#!/usr/bin/env python3
from __future__ import annotations

import fnmatch
import subprocess
from pathlib import Path


REPO_STYLE_DEFAULT_EXCLUDES = (
    "protocols/**/schema/**",
    "spec-lock/**/manifest.json",
    "protocols/**/generated/**",
    "tests/fixtures/**/expected/*.hex",
    "tests/fixtures/repo_style/**",
)

SOURCE_STYLE_DEFAULT_EXCLUDES = (
    "protocols/**/schema/**",
    "tests/fixtures/**",
    "spec-lock/**",
)

BINARY_EXTENSIONS = {
    ".bin",
    ".bmp",
    ".class",
    ".csv",
    ".dll",
    ".dylib",
    ".exe",
    ".gif",
    ".hex",
    ".ico",
    ".jpg",
    ".jpeg",
    ".pdf",
    ".png",
    ".so",
    ".tar",
    ".tgz",
    ".webp",
    ".zip",
}

TEXT_KIND_BY_SUFFIX = {
    ".cmake": "cmake",
    ".cpp": "cpp",
    ".css": "text",
    ".h": "cpp",
    ".hpp": "cpp",
    ".html": "text",
    ".ini": "text",
    ".json": "json",
    ".md": "markdown",
    ".py": "python",
    ".sh": "shell",
    ".txt": "text",
    ".xml": "text",
    ".yaml": "yaml",
    ".yml": "yaml",
}

SPECIAL_KIND_BY_NAME = {
    ".clang-format": "yaml",
    ".clang-tidy": "yaml",
    ".editorconfig": "text",
    ".gitignore": "text",
    "CMakeLists.txt": "cmake",
    "Dockerfile": "text",
}

MAX_LINE_LENGTH = {
    "cmake": 160,
    "cpp": 160,
    "json": 160,
    "markdown": 220,
    "python": 140,
    "shell": 160,
    "text": 160,
    "yaml": 160,
}

GENERATED_MARKERS = (
    "generated file",
    "generated by",
    "do not edit",
)


def repo_relative(path: Path, root: Path) -> str:
    return path.resolve().relative_to(root.resolve()).as_posix()


def matches_any(path: str, patterns: tuple[str, ...] | list[str]) -> bool:
    return any(fnmatch.fnmatch(path, pattern) for pattern in patterns)


def normalize_path_specs(path_specs: list[str], root: Path) -> list[str]:
    normalized: list[str] = []
    for raw in path_specs:
        candidate = Path(raw)
        if candidate.is_absolute():
            resolved = candidate.resolve()
            try:
                normalized.append(repo_relative(resolved, root))
            except ValueError:
                normalized.append(str(resolved))
            continue
        normalized.append(raw)
    return normalized


def tracked_files(root: Path, path_specs: list[str] | None = None) -> list[Path]:
    command = ["git", "ls-files"]
    if path_specs:
        command.extend(["--", *normalize_path_specs(path_specs, root)])
    result = subprocess.run(
        command,
        cwd=root,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        return []
    return [root / item for item in result.stdout.splitlines() if item]


def classify_kind(path: Path) -> str | None:
    if path.name in SPECIAL_KIND_BY_NAME:
        return SPECIAL_KIND_BY_NAME[path.name]
    return TEXT_KIND_BY_SUFFIX.get(path.suffix.lower())


def is_binary_extension(path: Path) -> bool:
    return path.suffix.lower() in BINARY_EXTENSIONS


def is_generated_path(path: Path) -> bool:
    return "generated" in path.parts


def has_generated_marker(text: str) -> bool:
    head = "\n".join(text.splitlines()[:8]).lower()
    return any(marker in head for marker in GENERATED_MARKERS)


def is_generated_file(path: Path, text: str) -> bool:
    return is_generated_path(path) and has_generated_marker(text)


def has_cr_only(raw: bytes) -> bool:
    return b"\r" in raw.replace(b"\r\n", b"")


def has_final_newline(raw: bytes) -> bool:
    return not raw or raw.endswith(b"\n")


def is_minified_like(path: Path, text: str) -> bool:
    if is_generated_path(path):
        return False
    lines = text.splitlines()
    nonempty = [line for line in lines if line.strip()]
    if not nonempty:
        return False

    longest = max(len(line) for line in nonempty)
    average = sum(len(line) for line in nonempty) / len(nonempty)

    if len(nonempty) <= 3 and longest > 300:
        return True
    if longest > 1000:
        return True
    if average > 300 and len(nonempty) < 20:
        return True
    return False


def excessive_blank_line_issue(path: Path, text: str) -> str | None:
    if is_generated_path(path):
        return None

    lines = text.splitlines()
    nonempty = [line for line in lines if line.strip()]
    blank_lines = len(lines) - len(nonempty)
    if blank_lines > max(20, len(nonempty) // 2):
        return "excessive blank-line ratio"

    consecutive = 0
    for line in lines:
        if line.strip():
            consecutive = 0
            continue
        consecutive += 1
        if consecutive >= 3:
            return "contains 3 or more consecutive blank lines"

    return None
