include(CMakeParseArguments)

function(moex_add_noarg_case_runner target_name)
    set(one_value_args SOURCE_DIR)
    set(multi_value_args CASES INCLUDE_DIRECTORIES LIBRARIES LABELS)
    cmake_parse_arguments(ARG "" "${one_value_args}" "${multi_value_args}" ${ARGN})

    if(NOT ARG_CASES)
        message(FATAL_ERROR "${target_name} requires at least one CASES entry")
    endif()

    set(case_sources)
    set(case_declarations)
    set(case_entries)
    foreach(case_spec IN LISTS ARG_CASES)
        string(FIND "${case_spec}" "=" separator)
        if(separator GREATER 0)
            string(SUBSTRING "${case_spec}" 0 ${separator} case_name)
            math(EXPR source_offset "${separator} + 1")
            string(SUBSTRING "${case_spec}" ${source_offset} -1 source_relative)
        elseif(ARG_SOURCE_DIR)
            set(case_name "${case_spec}")
            set(source_relative "${ARG_SOURCE_DIR}/${case_name}.cpp")
        else()
            message(FATAL_ERROR "Invalid ${target_name} case '${case_spec}'; expected name=source or SOURCE_DIR")
        endif()
        if(IS_ABSOLUTE "${source_relative}")
            set(source_path "${source_relative}")
        else()
            set(source_path "${MOEX_SOURCE_ROOT}/${source_relative}")
        endif()
        string(MAKE_C_IDENTIFIER "${target_name}_${case_name}" case_symbol)

        list(APPEND case_sources "${source_path}")
        set_property(SOURCE "${source_path}" APPEND PROPERTY COMPILE_DEFINITIONS "main=moex_case_${case_symbol}")
        string(APPEND case_declarations "int moex_case_${case_symbol}();\n")
        string(APPEND case_entries "    {\"${case_name}\", &moex_case_${case_symbol}},\n")
    endforeach()

    set(MOEX_CASE_DECLARATIONS "${case_declarations}")
    set(MOEX_CASE_ENTRIES "${case_entries}")
    set(runner_source "${CMAKE_CURRENT_BINARY_DIR}/generated/${target_name}_main.cpp")
    configure_file(
        "${MOEX_SOURCE_ROOT}/cmake/noarg_test_case_runner.cpp.in"
        "${runner_source}"
        @ONLY)

    add_executable(${target_name} "${runner_source}" ${case_sources})
    target_compile_features(${target_name} PRIVATE cxx_std_20)
    target_compile_definitions(${target_name} PRIVATE MOEX_SOURCE_ROOT="${MOEX_SOURCE_ROOT}")
    if(ARG_INCLUDE_DIRECTORIES)
        target_include_directories(${target_name} PRIVATE ${ARG_INCLUDE_DIRECTORIES})
    endif()
    if(ARG_LIBRARIES)
        target_link_libraries(${target_name} PRIVATE ${ARG_LIBRARIES})
    endif()
    set_property(TARGET ${target_name} PROPERTY RUNTIME_OUTPUT_DIRECTORY "${MOEX_BUILD_ROOT}/tests")

    foreach(case_spec IN LISTS ARG_CASES)
        string(FIND "${case_spec}" "=" separator)
        if(separator GREATER 0)
            string(SUBSTRING "${case_spec}" 0 ${separator} case_name)
        else()
            set(case_name "${case_spec}")
        endif()
        add_test(NAME ${case_name} COMMAND "$<TARGET_FILE:${target_name}>" --case "${case_name}")
        if(ARG_LABELS)
            set_tests_properties(${case_name} PROPERTIES LABELS "${ARG_LABELS}")
        endif()
    endforeach()
endfunction()
